// @generated by layers-codegen. do not edit.

//! Generated handlers and route table for the orchestrator, derived
//! from `orchestrator-spec/queries.json`. Each query in the spec
//! emits one axum handler function plus one route mount.

#![allow(
    missing_docs,
    clippy::too_many_lines,
    clippy::needless_pass_by_value,
    clippy::missing_errors_doc
)]

use axum::Json;
use axum::Router;
use axum::extract::{Query, State};
use axum::middleware::from_fn_with_state;
use axum::routing::get;
use serde::Deserialize;

use crate::auth::{Tier, require};
use crate::error::Result;
use crate::queries::{
    ByUri, Filter, ListResponse, RecordView, clamp_limit, fetch_one, list_table_filtered,
};
use crate::state::AppState;

/// `pub.layers.expression.getExpression` — fetch by AT-URI from `expressions`.
pub async fn get_expression(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "expressions", &q.uri).await?))
}

/// Query parameters for `pub.layers.expression.listExpressions`.
#[derive(Debug, Default, Deserialize)]
pub struct ListExpressionsParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.expression.listExpressions` — list rows from `expressions` with the spec's filters.
pub async fn list_expressions(
    State(state): State<AppState>,
    Query(q): Query<ListExpressionsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(&state, "expressions", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.corpus.getCorpus` — fetch by AT-URI from `corpora`.
pub async fn get_corpus(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "corpora", &q.uri).await?))
}

/// Query parameters for `pub.layers.corpus.listCorpora`.
#[derive(Debug, Default, Deserialize)]
pub struct ListCorporaParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.corpus.listCorpora` — list rows from `corpora` with the spec's filters.
pub async fn list_corpora(
    State(state): State<AppState>,
    Query(q): Query<ListCorporaParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(&state, "corpora", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.corpus.getMembership` — fetch by AT-URI from `corpus_memberships`.
pub async fn get_corpus_membership(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "corpus_memberships", &q.uri).await?))
}

/// Query parameters for `pub.layers.corpus.listMemberships`.
#[derive(Debug, Default, Deserialize)]
pub struct ListCorpusMembershipsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `corpusRef` filter.
    #[serde(rename = "corpusRef", default)]
    pub corpus_ref: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.corpus.listMemberships` — list rows from `corpus_memberships` with the spec's filters.
pub async fn list_corpus_memberships(
    State(state): State<AppState>,
    Query(q): Query<ListCorpusMembershipsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("corpusRef", q.corpus_ref.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "corpus_memberships",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.ontology.getOntology` — fetch by AT-URI from `ontologies`.
pub async fn get_ontology(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "ontologies", &q.uri).await?))
}

/// Query parameters for `pub.layers.ontology.listOntologies`.
#[derive(Debug, Default, Deserialize)]
pub struct ListOntologiesParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.ontology.listOntologies` — list rows from `ontologies` with the spec's filters.
pub async fn list_ontologies(
    State(state): State<AppState>,
    Query(q): Query<ListOntologiesParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(&state, "ontologies", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.ontology.getTypeDef` — fetch by AT-URI from `type_defs`.
pub async fn get_type_def(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "type_defs", &q.uri).await?))
}

/// Query parameters for `pub.layers.ontology.listTypeDefs`.
#[derive(Debug, Default, Deserialize)]
pub struct ListTypeDefsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `ontologyRef` filter.
    #[serde(rename = "ontologyRef", default)]
    pub ontology_ref: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.ontology.listTypeDefs` — list rows from `type_defs` with the spec's filters.
pub async fn list_type_defs(
    State(state): State<AppState>,
    Query(q): Query<ListTypeDefsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("ontologyRef", q.ontology_ref.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(&state, "type_defs", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.persona.getPersona` — fetch by AT-URI from `personas`.
pub async fn get_persona(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "personas", &q.uri).await?))
}

/// Query parameters for `pub.layers.persona.listPersonas`.
#[derive(Debug, Default, Deserialize)]
pub struct ListPersonasParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.persona.listPersonas` — list rows from `personas` with the spec's filters.
pub async fn list_personas(
    State(state): State<AppState>,
    Query(q): Query<ListPersonasParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(&state, "personas", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.annotation.getAnnotationLayer` — fetch by AT-URI from `annotation_layers`.
pub async fn get_annotation_layer(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "annotation_layers", &q.uri).await?))
}

/// Query parameters for `pub.layers.annotation.listAnnotationLayers`.
#[derive(Debug, Default, Deserialize)]
pub struct ListAnnotationLayersParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `expression` filter.
    #[serde(rename = "expression", default)]
    pub expression: Option<String>,
    /// `kind` filter.
    #[serde(rename = "kind", default)]
    pub kind: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.annotation.listAnnotationLayers` — list rows from `annotation_layers` with the spec's filters.
pub async fn list_annotation_layers(
    State(state): State<AppState>,
    Query(q): Query<ListAnnotationLayersParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("expression", q.expression.as_deref()),
        Filter::opt("kind", q.kind.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "annotation_layers",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.annotation.getClusterSet` — fetch by AT-URI from `cluster_sets`.
pub async fn get_cluster_set(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "cluster_sets", &q.uri).await?))
}

/// Query parameters for `pub.layers.annotation.listClusterSets`.
#[derive(Debug, Default, Deserialize)]
pub struct ListClusterSetsParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.annotation.listClusterSets` — list rows from `cluster_sets` with the spec's filters.
pub async fn list_cluster_sets(
    State(state): State<AppState>,
    Query(q): Query<ListClusterSetsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(&state, "cluster_sets", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.segmentation.getSegmentation` — fetch by AT-URI from `segmentations`.
pub async fn get_segmentation(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "segmentations", &q.uri).await?))
}

/// Query parameters for `pub.layers.segmentation.listSegmentations`.
#[derive(Debug, Default, Deserialize)]
pub struct ListSegmentationsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `expression` filter.
    #[serde(rename = "expression", default)]
    pub expression: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.segmentation.listSegmentations` — list rows from `segmentations` with the spec's filters.
pub async fn list_segmentations(
    State(state): State<AppState>,
    Query(q): Query<ListSegmentationsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("expression", q.expression.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "segmentations",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.alignment.getAlignment` — fetch by AT-URI from `alignments`.
pub async fn get_alignment(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "alignments", &q.uri).await?))
}

/// Query parameters for `pub.layers.alignment.listAlignments`.
#[derive(Debug, Default, Deserialize)]
pub struct ListAlignmentsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `source` filter.
    #[serde(rename = "source", default)]
    pub source: Option<String>,
    /// `target` filter.
    #[serde(rename = "target", default)]
    pub target: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.alignment.listAlignments` — list rows from `alignments` with the spec's filters.
pub async fn list_alignments(
    State(state): State<AppState>,
    Query(q): Query<ListAlignmentsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("source.recordRef", q.source.as_deref()),
        Filter::opt("target.recordRef", q.target.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(&state, "alignments", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.graph.getGraphNode` — fetch by AT-URI from `graph_nodes`.
pub async fn get_graph_node(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "graph_nodes", &q.uri).await?))
}

/// Query parameters for `pub.layers.graph.listGraphNodes`.
#[derive(Debug, Default, Deserialize)]
pub struct ListGraphNodesParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.graph.listGraphNodes` — list rows from `graph_nodes` with the spec's filters.
pub async fn list_graph_nodes(
    State(state): State<AppState>,
    Query(q): Query<ListGraphNodesParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(&state, "graph_nodes", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.graph.getGraphEdge` — fetch by AT-URI from `graph_edges`.
pub async fn get_graph_edge(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "graph_edges", &q.uri).await?))
}

/// Query parameters for `pub.layers.graph.listGraphEdges`.
#[derive(Debug, Default, Deserialize)]
pub struct ListGraphEdgesParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `source` filter.
    #[serde(rename = "source", default)]
    pub source: Option<String>,
    /// `target` filter.
    #[serde(rename = "target", default)]
    pub target: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.graph.listGraphEdges` — list rows from `graph_edges` with the spec's filters.
pub async fn list_graph_edges(
    State(state): State<AppState>,
    Query(q): Query<ListGraphEdgesParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("source.recordRef", q.source.as_deref()),
        Filter::opt("target.recordRef", q.target.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(&state, "graph_edges", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.graph.getGraphEdgeSet` — fetch by AT-URI from `graph_edge_sets`.
pub async fn get_graph_edge_set(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "graph_edge_sets", &q.uri).await?))
}

/// Query parameters for `pub.layers.graph.listGraphEdgeSets`.
#[derive(Debug, Default, Deserialize)]
pub struct ListGraphEdgeSetsParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.graph.listGraphEdgeSets` — list rows from `graph_edge_sets` with the spec's filters.
pub async fn list_graph_edge_sets(
    State(state): State<AppState>,
    Query(q): Query<ListGraphEdgeSetsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(
            &state,
            "graph_edge_sets",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.judgment.getExperimentDef` — fetch by AT-URI from `experiment_defs`.
pub async fn get_experiment_def(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "experiment_defs", &q.uri).await?))
}

/// Query parameters for `pub.layers.judgment.listExperimentDefs`.
#[derive(Debug, Default, Deserialize)]
pub struct ListExperimentDefsParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.judgment.listExperimentDefs` — list rows from `experiment_defs` with the spec's filters.
pub async fn list_experiment_defs(
    State(state): State<AppState>,
    Query(q): Query<ListExperimentDefsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(
            &state,
            "experiment_defs",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.judgment.getJudgmentSet` — fetch by AT-URI from `judgment_sets`.
pub async fn get_judgment_set(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "judgment_sets", &q.uri).await?))
}

/// Query parameters for `pub.layers.judgment.listJudgmentSets`.
#[derive(Debug, Default, Deserialize)]
pub struct ListJudgmentSetsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `experimentRef` filter.
    #[serde(rename = "experimentRef", default)]
    pub experiment_ref: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.judgment.listJudgmentSets` — list rows from `judgment_sets` with the spec's filters.
pub async fn list_judgment_sets(
    State(state): State<AppState>,
    Query(q): Query<ListJudgmentSetsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("experimentRef", q.experiment_ref.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "judgment_sets",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.judgment.getAgreementReport` — fetch by AT-URI from `agreement_reports`.
pub async fn get_agreement_report(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "agreement_reports", &q.uri).await?))
}

/// Query parameters for `pub.layers.judgment.listAgreementReports`.
#[derive(Debug, Default, Deserialize)]
pub struct ListAgreementReportsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `experimentRef` filter.
    #[serde(rename = "experimentRef", default)]
    pub experiment_ref: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.judgment.listAgreementReports` — list rows from `agreement_reports` with the spec's filters.
pub async fn list_agreement_reports(
    State(state): State<AppState>,
    Query(q): Query<ListAgreementReportsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("experimentRef", q.experiment_ref.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "agreement_reports",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.resource.getCollection` — fetch by AT-URI from `resource_collections`.
pub async fn get_collection(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(
        fetch_one(&state, "resource_collections", &q.uri).await?,
    ))
}

/// Query parameters for `pub.layers.resource.listCollections`.
#[derive(Debug, Default, Deserialize)]
pub struct ListCollectionsParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.resource.listCollections` — list rows from `resource_collections` with the spec's filters.
pub async fn list_collections(
    State(state): State<AppState>,
    Query(q): Query<ListCollectionsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(
            &state,
            "resource_collections",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.resource.getCollectionMembership` — fetch by AT-URI from `resource_collection_memberships`.
pub async fn get_collection_membership(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(
        fetch_one(&state, "resource_collection_memberships", &q.uri).await?,
    ))
}

/// Query parameters for `pub.layers.resource.listCollectionMemberships`.
#[derive(Debug, Default, Deserialize)]
pub struct ListCollectionMembershipsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `collectionRef` filter.
    #[serde(rename = "collectionRef", default)]
    pub collection_ref: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.resource.listCollectionMemberships` — list rows from `resource_collection_memberships` with the spec's filters.
pub async fn list_collection_memberships(
    State(state): State<AppState>,
    Query(q): Query<ListCollectionMembershipsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("collectionRef", q.collection_ref.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "resource_collection_memberships",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.resource.getEntry` — fetch by AT-URI from `resource_entries`.
pub async fn get_entry(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "resource_entries", &q.uri).await?))
}

/// Query parameters for `pub.layers.resource.listEntries`.
#[derive(Debug, Default, Deserialize)]
pub struct ListEntriesParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.resource.listEntries` — list rows from `resource_entries` with the spec's filters.
pub async fn list_entries(
    State(state): State<AppState>,
    Query(q): Query<ListEntriesParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(
            &state,
            "resource_entries",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.resource.getFilling` — fetch by AT-URI from `resource_fillings`.
pub async fn get_filling(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "resource_fillings", &q.uri).await?))
}

/// Query parameters for `pub.layers.resource.listFillings`.
#[derive(Debug, Default, Deserialize)]
pub struct ListFillingsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `templateRef` filter.
    #[serde(rename = "templateRef", default)]
    pub template_ref: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.resource.listFillings` — list rows from `resource_fillings` with the spec's filters.
pub async fn list_fillings(
    State(state): State<AppState>,
    Query(q): Query<ListFillingsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("templateRef", q.template_ref.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "resource_fillings",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.resource.getTemplate` — fetch by AT-URI from `resource_templates`.
pub async fn get_template(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "resource_templates", &q.uri).await?))
}

/// Query parameters for `pub.layers.resource.listTemplates`.
#[derive(Debug, Default, Deserialize)]
pub struct ListTemplatesParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.resource.listTemplates` — list rows from `resource_templates` with the spec's filters.
pub async fn list_templates(
    State(state): State<AppState>,
    Query(q): Query<ListTemplatesParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(
            &state,
            "resource_templates",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.resource.getTemplateComposition` — fetch by AT-URI from `resource_template_compositions`.
pub async fn get_template_composition(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(
        fetch_one(&state, "resource_template_compositions", &q.uri).await?,
    ))
}

/// Query parameters for `pub.layers.resource.listTemplateCompositions`.
#[derive(Debug, Default, Deserialize)]
pub struct ListTemplateCompositionsParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.resource.listTemplateCompositions` — list rows from `resource_template_compositions` with the spec's filters.
pub async fn list_template_compositions(
    State(state): State<AppState>,
    Query(q): Query<ListTemplateCompositionsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(
            &state,
            "resource_template_compositions",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.eprint.getEprint` — fetch by AT-URI from `eprints`.
pub async fn get_eprint(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "eprints", &q.uri).await?))
}

/// Query parameters for `pub.layers.eprint.listEprints`.
#[derive(Debug, Default, Deserialize)]
pub struct ListEprintsParams {
    #[serde(default)]
    pub did: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.eprint.listEprints` — list rows from `eprints` with the spec's filters.
pub async fn list_eprints(
    State(state): State<AppState>,
    Query(q): Query<ListEprintsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [Filter::opt("did", q.did.as_deref())];
    Ok(Json(
        list_table_filtered(&state, "eprints", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.eprint.getDataLink` — fetch by AT-URI from `data_links`.
pub async fn get_data_link(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "data_links", &q.uri).await?))
}

/// Query parameters for `pub.layers.eprint.listDataLinks`.
#[derive(Debug, Default, Deserialize)]
pub struct ListDataLinksParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `eprintUri` filter.
    #[serde(rename = "eprintUri", default)]
    pub eprint_uri: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.eprint.listDataLinks` — list rows from `data_links` with the spec's filters.
pub async fn list_data_links(
    State(state): State<AppState>,
    Query(q): Query<ListDataLinksParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("eprintUri", q.eprint_uri.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(&state, "data_links", &filters, q.cursor.as_deref(), limit).await?,
    ))
}

/// `pub.layers.media.getMedia` — fetch by AT-URI from `media_records`.
pub async fn get_media(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "media_records", &q.uri).await?))
}

/// Query parameters for `pub.layers.media.listMedia`.
#[derive(Debug, Default, Deserialize)]
pub struct ListMediaParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `mimeType` filter.
    #[serde(rename = "mimeType", default)]
    pub mime_type: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.media.listMedia` — list rows from `media_records` with the spec's filters.
pub async fn list_media(
    State(state): State<AppState>,
    Query(q): Query<ListMediaParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("mimeType", q.mime_type.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "media_records",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// `pub.layers.changelog.getEntry` — fetch by AT-URI from `changelog_entries`.
pub async fn get_changelog_entry(
    State(state): State<AppState>,
    Query(q): Query<ByUri>,
) -> Result<Json<RecordView>> {
    Ok(Json(fetch_one(&state, "changelog_entries", &q.uri).await?))
}

/// Query parameters for `pub.layers.changelog.listEntries`.
#[derive(Debug, Default, Deserialize)]
pub struct ListChangelogEntriesParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `subject` filter.
    #[serde(rename = "subject", default)]
    pub subject: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.changelog.listEntries` — list rows from `changelog_entries` with the spec's filters.
pub async fn list_changelog_entries(
    State(state): State<AppState>,
    Query(q): Query<ListChangelogEntriesParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("subject", q.subject.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "changelog_entries",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// Query parameters for `pub.layers.integration.listExternal`.
#[derive(Debug, Default, Deserialize)]
pub struct ListExternalRecordsParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `nsid` filter.
    #[serde(rename = "nsid", default)]
    pub nsid: Option<String>,
    /// `nsidPrefix` filter.
    #[serde(rename = "nsidPrefix", default)]
    pub nsid_prefix: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.integration.listExternal` — list rows from `external_records` with the spec's filters.
pub async fn list_external_records(
    State(state): State<AppState>,
    Query(q): Query<ListExternalRecordsParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("nsid", q.nsid.as_deref()),
        Filter::opt("nsidPrefix", q.nsid_prefix.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "external_records",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// Query parameters for `pub.layers.changelog.listByCollection`.
#[derive(Debug, Default, Deserialize)]
pub struct ListChangelogByCollectionParams {
    #[serde(default)]
    pub did: Option<String>,
    /// `subjectCollection` filter.
    #[serde(rename = "subjectCollection", default)]
    pub subject_collection: Option<String>,
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub limit: Option<i64>,
}

/// `pub.layers.changelog.listByCollection` — list rows from `changelog_entries` with the spec's filters.
pub async fn list_changelog_by_collection(
    State(state): State<AppState>,
    Query(q): Query<ListChangelogByCollectionParams>,
) -> Result<Json<ListResponse>> {
    let limit = clamp_limit(q.limit);
    let filters = [
        Filter::opt("did", q.did.as_deref()),
        Filter::opt("subjectCollection", q.subject_collection.as_deref()),
    ];
    Ok(Json(
        list_table_filtered(
            &state,
            "changelog_entries",
            &filters,
            q.cursor.as_deref(),
            limit,
        )
        .await?,
    ))
}

/// Mount every XRPC route declared in `orchestrator-spec/queries.json`.
pub fn xrpc_routes(state: AppState) -> Router<AppState> {
    Router::new()
        .route(
            "/xrpc/pub.layers.expression.getExpression",
            get(get_expression).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.expression.getExpression"),
            )),
        )
        .route(
            "/xrpc/pub.layers.expression.listExpressions",
            get(list_expressions).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.expression.listExpressions"),
            )),
        )
        .route(
            "/xrpc/pub.layers.corpus.getCorpus",
            get(get_corpus).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.corpus.getCorpus"),
            )),
        )
        .route(
            "/xrpc/pub.layers.corpus.listCorpora",
            get(list_corpora).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.corpus.listCorpora"),
            )),
        )
        .route(
            "/xrpc/pub.layers.corpus.getMembership",
            get(get_corpus_membership).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.corpus.getMembership"),
            )),
        )
        .route(
            "/xrpc/pub.layers.corpus.listMemberships",
            get(list_corpus_memberships).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.corpus.listMemberships"),
            )),
        )
        .route(
            "/xrpc/pub.layers.ontology.getOntology",
            get(get_ontology).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.ontology.getOntology"),
            )),
        )
        .route(
            "/xrpc/pub.layers.ontology.listOntologies",
            get(list_ontologies).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.ontology.listOntologies"),
            )),
        )
        .route(
            "/xrpc/pub.layers.ontology.getTypeDef",
            get(get_type_def).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.ontology.getTypeDef"),
            )),
        )
        .route(
            "/xrpc/pub.layers.ontology.listTypeDefs",
            get(list_type_defs).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.ontology.listTypeDefs"),
            )),
        )
        .route(
            "/xrpc/pub.layers.persona.getPersona",
            get(get_persona).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.persona.getPersona"),
            )),
        )
        .route(
            "/xrpc/pub.layers.persona.listPersonas",
            get(list_personas).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.persona.listPersonas"),
            )),
        )
        .route(
            "/xrpc/pub.layers.annotation.getAnnotationLayer",
            get(get_annotation_layer).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.annotation.getAnnotationLayer"),
            )),
        )
        .route(
            "/xrpc/pub.layers.annotation.listAnnotationLayers",
            get(list_annotation_layers).route_layer(from_fn_with_state(
                state.clone(),
                require(
                    Tier::PublicRead,
                    "pub.layers.annotation.listAnnotationLayers",
                ),
            )),
        )
        .route(
            "/xrpc/pub.layers.annotation.getClusterSet",
            get(get_cluster_set).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.annotation.getClusterSet"),
            )),
        )
        .route(
            "/xrpc/pub.layers.annotation.listClusterSets",
            get(list_cluster_sets).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.annotation.listClusterSets"),
            )),
        )
        .route(
            "/xrpc/pub.layers.segmentation.getSegmentation",
            get(get_segmentation).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.segmentation.getSegmentation"),
            )),
        )
        .route(
            "/xrpc/pub.layers.segmentation.listSegmentations",
            get(list_segmentations).route_layer(from_fn_with_state(
                state.clone(),
                require(
                    Tier::PublicRead,
                    "pub.layers.segmentation.listSegmentations",
                ),
            )),
        )
        .route(
            "/xrpc/pub.layers.alignment.getAlignment",
            get(get_alignment).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.alignment.getAlignment"),
            )),
        )
        .route(
            "/xrpc/pub.layers.alignment.listAlignments",
            get(list_alignments).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.alignment.listAlignments"),
            )),
        )
        .route(
            "/xrpc/pub.layers.graph.getGraphNode",
            get(get_graph_node).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.graph.getGraphNode"),
            )),
        )
        .route(
            "/xrpc/pub.layers.graph.listGraphNodes",
            get(list_graph_nodes).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.graph.listGraphNodes"),
            )),
        )
        .route(
            "/xrpc/pub.layers.graph.getGraphEdge",
            get(get_graph_edge).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.graph.getGraphEdge"),
            )),
        )
        .route(
            "/xrpc/pub.layers.graph.listGraphEdges",
            get(list_graph_edges).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.graph.listGraphEdges"),
            )),
        )
        .route(
            "/xrpc/pub.layers.graph.getGraphEdgeSet",
            get(get_graph_edge_set).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.graph.getGraphEdgeSet"),
            )),
        )
        .route(
            "/xrpc/pub.layers.graph.listGraphEdgeSets",
            get(list_graph_edge_sets).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.graph.listGraphEdgeSets"),
            )),
        )
        .route(
            "/xrpc/pub.layers.judgment.getExperimentDef",
            get(get_experiment_def).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.judgment.getExperimentDef"),
            )),
        )
        .route(
            "/xrpc/pub.layers.judgment.listExperimentDefs",
            get(list_experiment_defs).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.judgment.listExperimentDefs"),
            )),
        )
        .route(
            "/xrpc/pub.layers.judgment.getJudgmentSet",
            get(get_judgment_set).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.judgment.getJudgmentSet"),
            )),
        )
        .route(
            "/xrpc/pub.layers.judgment.listJudgmentSets",
            get(list_judgment_sets).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.judgment.listJudgmentSets"),
            )),
        )
        .route(
            "/xrpc/pub.layers.judgment.getAgreementReport",
            get(get_agreement_report).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.judgment.getAgreementReport"),
            )),
        )
        .route(
            "/xrpc/pub.layers.judgment.listAgreementReports",
            get(list_agreement_reports).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.judgment.listAgreementReports"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.getCollection",
            get(get_collection).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.getCollection"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.listCollections",
            get(list_collections).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.listCollections"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.getCollectionMembership",
            get(get_collection_membership).route_layer(from_fn_with_state(
                state.clone(),
                require(
                    Tier::PublicRead,
                    "pub.layers.resource.getCollectionMembership",
                ),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.listCollectionMemberships",
            get(list_collection_memberships).route_layer(from_fn_with_state(
                state.clone(),
                require(
                    Tier::PublicRead,
                    "pub.layers.resource.listCollectionMemberships",
                ),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.getEntry",
            get(get_entry).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.getEntry"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.listEntries",
            get(list_entries).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.listEntries"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.getFilling",
            get(get_filling).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.getFilling"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.listFillings",
            get(list_fillings).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.listFillings"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.getTemplate",
            get(get_template).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.getTemplate"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.listTemplates",
            get(list_templates).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.resource.listTemplates"),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.getTemplateComposition",
            get(get_template_composition).route_layer(from_fn_with_state(
                state.clone(),
                require(
                    Tier::PublicRead,
                    "pub.layers.resource.getTemplateComposition",
                ),
            )),
        )
        .route(
            "/xrpc/pub.layers.resource.listTemplateCompositions",
            get(list_template_compositions).route_layer(from_fn_with_state(
                state.clone(),
                require(
                    Tier::PublicRead,
                    "pub.layers.resource.listTemplateCompositions",
                ),
            )),
        )
        .route(
            "/xrpc/pub.layers.eprint.getEprint",
            get(get_eprint).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.eprint.getEprint"),
            )),
        )
        .route(
            "/xrpc/pub.layers.eprint.listEprints",
            get(list_eprints).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.eprint.listEprints"),
            )),
        )
        .route(
            "/xrpc/pub.layers.eprint.getDataLink",
            get(get_data_link).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.eprint.getDataLink"),
            )),
        )
        .route(
            "/xrpc/pub.layers.eprint.listDataLinks",
            get(list_data_links).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.eprint.listDataLinks"),
            )),
        )
        .route(
            "/xrpc/pub.layers.media.getMedia",
            get(get_media).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.media.getMedia"),
            )),
        )
        .route(
            "/xrpc/pub.layers.media.listMedia",
            get(list_media).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.media.listMedia"),
            )),
        )
        .route(
            "/xrpc/pub.layers.changelog.getEntry",
            get(get_changelog_entry).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.changelog.getEntry"),
            )),
        )
        .route(
            "/xrpc/pub.layers.changelog.listEntries",
            get(list_changelog_entries).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.changelog.listEntries"),
            )),
        )
        .route(
            "/xrpc/pub.layers.integration.listExternal",
            get(list_external_records).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.integration.listExternal"),
            )),
        )
        .route(
            "/xrpc/pub.layers.changelog.listByCollection",
            get(list_changelog_by_collection).route_layer(from_fn_with_state(
                state.clone(),
                require(Tier::PublicRead, "pub.layers.changelog.listByCollection"),
            )),
        )
}
