// @generated by layers-codegen. do not edit.

//! Wire field names for every `pub.layers.*` record kind, one module
//! per record. Hand-written SQL that reads a record's JSONB body by
//! key (e.g. the observer's `record->>'corpusRef'`) references these
//! constants, so a lexicon field rename regenerates the constant and
//! the drift gate catches any stale reference.

/// Field names for `pub.layers.judgment.agreementReport`.
pub mod agreement_report {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `experimentRef` property.
    pub const EXPERIMENT_REF: &str = "experimentRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `judgmentSetRefs` property.
    pub const JUDGMENT_SET_REFS: &str = "judgmentSetRefs";
    /// Wire name of the `metric` property.
    pub const METRIC: &str = "metric";
    /// Wire name of the `metricUri` property.
    pub const METRIC_URI: &str = "metricUri";
    /// Wire name of the `numAnnotators` property.
    pub const NUM_ANNOTATORS: &str = "numAnnotators";
    /// Wire name of the `numItems` property.
    pub const NUM_ITEMS: &str = "numItems";
    /// Wire name of the `value` property.
    pub const VALUE: &str = "value";
}

/// Field names for `pub.layers.alignment.alignment`.
pub mod alignment {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `expression` property.
    pub const EXPRESSION: &str = "expression";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `kind` property.
    pub const KIND: &str = "kind";
    /// Wire name of the `kindUri` property.
    pub const KIND_URI: &str = "kindUri";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `links` property.
    pub const LINKS: &str = "links";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `source` property.
    pub const SOURCE: &str = "source";
    /// Wire name of the `sourceLang` property.
    pub const SOURCE_LANG: &str = "sourceLang";
    /// Wire name of the `subkind` property.
    pub const SUBKIND: &str = "subkind";
    /// Wire name of the `subkindUri` property.
    pub const SUBKIND_URI: &str = "subkindUri";
    /// Wire name of the `target` property.
    pub const TARGET: &str = "target";
    /// Wire name of the `targetLang` property.
    pub const TARGET_LANG: &str = "targetLang";
}

/// Field names for `pub.layers.annotation.annotationLayer`.
pub mod annotation_layer {
    /// Wire name of the `alternativesRef` property.
    pub const ALTERNATIVES_REF: &str = "alternativesRef";
    /// Wire name of the `annotations` property.
    pub const ANNOTATIONS: &str = "annotations";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `expression` property.
    pub const EXPRESSION: &str = "expression";
    /// Wire name of the `formalism` property.
    pub const FORMALISM: &str = "formalism";
    /// Wire name of the `formalismUri` property.
    pub const FORMALISM_URI: &str = "formalismUri";
    /// Wire name of the `kind` property.
    pub const KIND: &str = "kind";
    /// Wire name of the `kindUri` property.
    pub const KIND_URI: &str = "kindUri";
    /// Wire name of the `labelSet` property.
    pub const LABEL_SET: &str = "labelSet";
    /// Wire name of the `languages` property.
    pub const LANGUAGES: &str = "languages";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `ontologyRef` property.
    pub const ONTOLOGY_REF: &str = "ontologyRef";
    /// Wire name of the `parentLayerRef` property.
    pub const PARENT_LAYER_REF: &str = "parentLayerRef";
    /// Wire name of the `rank` property.
    pub const RANK: &str = "rank";
    /// Wire name of the `sourceMethod` property.
    pub const SOURCE_METHOD: &str = "sourceMethod";
    /// Wire name of the `sourceMethodUri` property.
    pub const SOURCE_METHOD_URI: &str = "sourceMethodUri";
    /// Wire name of the `subkind` property.
    pub const SUBKIND: &str = "subkind";
    /// Wire name of the `subkindUri` property.
    pub const SUBKIND_URI: &str = "subkindUri";
    /// Wire name of the `tokenizationId` property.
    pub const TOKENIZATION_ID: &str = "tokenizationId";
}

/// Field names for `pub.layers.changelog.entry`.
pub mod changelog_entry {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `previousVersion` property.
    pub const PREVIOUS_VERSION: &str = "previousVersion";
    /// Wire name of the `sections` property.
    pub const SECTIONS: &str = "sections";
    /// Wire name of the `subject` property.
    pub const SUBJECT: &str = "subject";
    /// Wire name of the `subjectCollection` property.
    pub const SUBJECT_COLLECTION: &str = "subjectCollection";
    /// Wire name of the `summary` property.
    pub const SUMMARY: &str = "summary";
    /// Wire name of the `version` property.
    pub const VERSION: &str = "version";
}

/// Field names for `pub.layers.annotation.clusterSet`.
pub mod cluster_set {
    /// Wire name of the `clusters` property.
    pub const CLUSTERS: &str = "clusters";
    /// Wire name of the `corpusRef` property.
    pub const CORPUS_REF: &str = "corpusRef";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `expression` property.
    pub const EXPRESSION: &str = "expression";
    /// Wire name of the `expressionRefs` property.
    pub const EXPRESSION_REFS: &str = "expressionRefs";
    /// Wire name of the `kind` property.
    pub const KIND: &str = "kind";
    /// Wire name of the `kindUri` property.
    pub const KIND_URI: &str = "kindUri";
    /// Wire name of the `layerRef` property.
    pub const LAYER_REF: &str = "layerRef";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
}

/// Field names for `pub.layers.resource.collection`.
pub mod collection {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `kind` property.
    pub const KIND: &str = "kind";
    /// Wire name of the `kindUri` property.
    pub const KIND_URI: &str = "kindUri";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `languages` property.
    pub const LANGUAGES: &str = "languages";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `name` property.
    pub const NAME: &str = "name";
    /// Wire name of the `ontologyRef` property.
    pub const ONTOLOGY_REF: &str = "ontologyRef";
    /// Wire name of the `version` property.
    pub const VERSION: &str = "version";
}

/// Field names for `pub.layers.resource.collectionMembership`.
pub mod collection_membership {
    /// Wire name of the `collectionRef` property.
    pub const COLLECTION_REF: &str = "collectionRef";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `entryRef` property.
    pub const ENTRY_REF: &str = "entryRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `ordinal` property.
    pub const ORDINAL: &str = "ordinal";
}

/// Field names for `pub.layers.corpus.corpus`.
pub mod corpus {
    /// Wire name of the `annotationDesign` property.
    pub const ANNOTATION_DESIGN: &str = "annotationDesign";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `domain` property.
    pub const DOMAIN: &str = "domain";
    /// Wire name of the `domainUri` property.
    pub const DOMAIN_URI: &str = "domainUri";
    /// Wire name of the `eprintRefs` property.
    pub const EPRINT_REFS: &str = "eprintRefs";
    /// Wire name of the `expressionCount` property.
    pub const EXPRESSION_COUNT: &str = "expressionCount";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `languages` property.
    pub const LANGUAGES: &str = "languages";
    /// Wire name of the `license` property.
    pub const LICENSE: &str = "license";
    /// Wire name of the `name` property.
    pub const NAME: &str = "name";
    /// Wire name of the `ontologyRefs` property.
    pub const ONTOLOGY_REFS: &str = "ontologyRefs";
    /// Wire name of the `version` property.
    pub const VERSION: &str = "version";
}

/// Field names for `pub.layers.corpus.membership`.
pub mod corpus_membership {
    /// Wire name of the `corpusRef` property.
    pub const CORPUS_REF: &str = "corpusRef";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `expressionRef` property.
    pub const EXPRESSION_REF: &str = "expressionRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `ordinal` property.
    pub const ORDINAL: &str = "ordinal";
    /// Wire name of the `split` property.
    pub const SPLIT: &str = "split";
    /// Wire name of the `splitUri` property.
    pub const SPLIT_URI: &str = "splitUri";
}

/// Field names for `pub.layers.eprint.dataLink`.
pub mod data_link {
    /// Wire name of the `annotationRefs` property.
    pub const ANNOTATION_REFS: &str = "annotationRefs";
    /// Wire name of the `corpusRef` property.
    pub const CORPUS_REF: &str = "corpusRef";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `dataKind` property.
    pub const DATA_KIND: &str = "dataKind";
    /// Wire name of the `dataKindUri` property.
    pub const DATA_KIND_URI: &str = "dataKindUri";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `eprintDid` property.
    pub const EPRINT_DID: &str = "eprintDid";
    /// Wire name of the `eprintUri` property.
    pub const EPRINT_URI: &str = "eprintUri";
    /// Wire name of the `expressionRefs` property.
    pub const EXPRESSION_REFS: &str = "expressionRefs";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `paperSection` property.
    pub const PAPER_SECTION: &str = "paperSection";
    /// Wire name of the `reproducibility` property.
    pub const REPRODUCIBILITY: &str = "reproducibility";
}

/// Field names for `pub.layers.resource.entry`.
pub mod entry {
    /// Wire name of the `components` property.
    pub const COMPONENTS: &str = "components";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `form` property.
    pub const FORM: &str = "form";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `languages` property.
    pub const LANGUAGES: &str = "languages";
    /// Wire name of the `lemma` property.
    pub const LEMMA: &str = "lemma";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `mweKind` property.
    pub const MWE_KIND: &str = "mweKind";
    /// Wire name of the `mweKindUri` property.
    pub const MWE_KIND_URI: &str = "mweKindUri";
    /// Wire name of the `ontologyTypeRef` property.
    pub const ONTOLOGY_TYPE_REF: &str = "ontologyTypeRef";
    /// Wire name of the `sourceRef` property.
    pub const SOURCE_REF: &str = "sourceRef";
}

/// Field names for `pub.layers.eprint.eprint`.
pub mod eprint {
    /// Wire name of the `annotationRefs` property.
    pub const ANNOTATION_REFS: &str = "annotationRefs";
    /// Wire name of the `citation` property.
    pub const CITATION: &str = "citation";
    /// Wire name of the `corpusRef` property.
    pub const CORPUS_REF: &str = "corpusRef";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `eprintIdentifier` property.
    pub const EPRINT_IDENTIFIER: &str = "eprintIdentifier";
    /// Wire name of the `eprintIdentifierType` property.
    pub const EPRINT_IDENTIFIER_TYPE: &str = "eprintIdentifierType";
    /// Wire name of the `eprintIdentifierTypeUri` property.
    pub const EPRINT_IDENTIFIER_TYPE_URI: &str = "eprintIdentifierTypeUri";
    /// Wire name of the `eprintUri` property.
    pub const EPRINT_URI: &str = "eprintUri";
    /// Wire name of the `expressionRefs` property.
    pub const EXPRESSION_REFS: &str = "expressionRefs";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `linkType` property.
    pub const LINK_TYPE: &str = "linkType";
    /// Wire name of the `linkTypeUri` property.
    pub const LINK_TYPE_URI: &str = "linkTypeUri";
    /// Wire name of the `platformEprintRef` property.
    pub const PLATFORM_EPRINT_REF: &str = "platformEprintRef";
}

/// Field names for `pub.layers.judgment.experimentDef`.
pub mod experiment_def {
    /// Wire name of the `collectionRefs` property.
    pub const COLLECTION_REFS: &str = "collectionRefs";
    /// Wire name of the `corpusRef` property.
    pub const CORPUS_REF: &str = "corpusRef";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `design` property.
    pub const DESIGN: &str = "design";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `guidelines` property.
    pub const GUIDELINES: &str = "guidelines";
    /// Wire name of the `guidelinesFormat` property.
    pub const GUIDELINES_FORMAT: &str = "guidelinesFormat";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `labels` property.
    pub const LABELS: &str = "labels";
    /// Wire name of the `measureType` property.
    pub const MEASURE_TYPE: &str = "measureType";
    /// Wire name of the `measureTypeUri` property.
    pub const MEASURE_TYPE_URI: &str = "measureTypeUri";
    /// Wire name of the `name` property.
    pub const NAME: &str = "name";
    /// Wire name of the `ontologyRef` property.
    pub const ONTOLOGY_REF: &str = "ontologyRef";
    /// Wire name of the `personaRef` property.
    pub const PERSONA_REF: &str = "personaRef";
    /// Wire name of the `presentation` property.
    pub const PRESENTATION: &str = "presentation";
    /// Wire name of the `recordingMethods` property.
    pub const RECORDING_METHODS: &str = "recordingMethods";
    /// Wire name of the `scaleMax` property.
    pub const SCALE_MAX: &str = "scaleMax";
    /// Wire name of the `scaleMin` property.
    pub const SCALE_MIN: &str = "scaleMin";
    /// Wire name of the `taskType` property.
    pub const TASK_TYPE: &str = "taskType";
    /// Wire name of the `taskTypeUri` property.
    pub const TASK_TYPE_URI: &str = "taskTypeUri";
    /// Wire name of the `templateRefs` property.
    pub const TEMPLATE_REFS: &str = "templateRefs";
}

/// Field names for `pub.layers.expression.expression`.
pub mod expression {
    /// Wire name of the `anchor` property.
    pub const ANCHOR: &str = "anchor";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `eprintRef` property.
    pub const EPRINT_REF: &str = "eprintRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `id` property.
    pub const ID: &str = "id";
    /// Wire name of the `kind` property.
    pub const KIND: &str = "kind";
    /// Wire name of the `kindUri` property.
    pub const KIND_URI: &str = "kindUri";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `languages` property.
    pub const LANGUAGES: &str = "languages";
    /// Wire name of the `mediaBlob` property.
    pub const MEDIA_BLOB: &str = "mediaBlob";
    /// Wire name of the `mediaRef` property.
    pub const MEDIA_REF: &str = "mediaRef";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `parentRef` property.
    pub const PARENT_REF: &str = "parentRef";
    /// Wire name of the `sourceRef` property.
    pub const SOURCE_REF: &str = "sourceRef";
    /// Wire name of the `sourceUrl` property.
    pub const SOURCE_URL: &str = "sourceUrl";
    /// Wire name of the `text` property.
    pub const TEXT: &str = "text";
}

/// Field names for `pub.layers.resource.filling`.
pub mod filling {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `expressionRef` property.
    pub const EXPRESSION_REF: &str = "expressionRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `renderedText` property.
    pub const RENDERED_TEXT: &str = "renderedText";
    /// Wire name of the `slotFillings` property.
    pub const SLOT_FILLINGS: &str = "slotFillings";
    /// Wire name of the `strategy` property.
    pub const STRATEGY: &str = "strategy";
    /// Wire name of the `strategyUri` property.
    pub const STRATEGY_URI: &str = "strategyUri";
    /// Wire name of the `templateRef` property.
    pub const TEMPLATE_REF: &str = "templateRef";
}

/// Field names for `pub.layers.graph.graphEdge`.
pub mod graph_edge {
    /// Wire name of the `confidence` property.
    pub const CONFIDENCE: &str = "confidence";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `edgeType` property.
    pub const EDGE_TYPE: &str = "edgeType";
    /// Wire name of the `edgeTypeUri` property.
    pub const EDGE_TYPE_URI: &str = "edgeTypeUri";
    /// Wire name of the `label` property.
    pub const LABEL: &str = "label";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `ordinal` property.
    pub const ORDINAL: &str = "ordinal";
    /// Wire name of the `properties` property.
    pub const PROPERTIES: &str = "properties";
    /// Wire name of the `source` property.
    pub const SOURCE: &str = "source";
    /// Wire name of the `target` property.
    pub const TARGET: &str = "target";
}

/// Field names for `pub.layers.graph.graphEdgeSet`.
pub mod graph_edge_set {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `edgeType` property.
    pub const EDGE_TYPE: &str = "edgeType";
    /// Wire name of the `edgeTypeUri` property.
    pub const EDGE_TYPE_URI: &str = "edgeTypeUri";
    /// Wire name of the `edges` property.
    pub const EDGES: &str = "edges";
    /// Wire name of the `expression` property.
    pub const EXPRESSION: &str = "expression";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
}

/// Field names for `pub.layers.graph.graphNode`.
pub mod graph_node {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `label` property.
    pub const LABEL: &str = "label";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `nodeType` property.
    pub const NODE_TYPE: &str = "nodeType";
    /// Wire name of the `nodeTypeUri` property.
    pub const NODE_TYPE_URI: &str = "nodeTypeUri";
    /// Wire name of the `properties` property.
    pub const PROPERTIES: &str = "properties";
}

/// Field names for `pub.layers.judgment.judgmentSet`.
pub mod judgment_set {
    /// Wire name of the `agent` property.
    pub const AGENT: &str = "agent";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `experimentRef` property.
    pub const EXPERIMENT_REF: &str = "experimentRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `judgments` property.
    pub const JUDGMENTS: &str = "judgments";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
}

/// Field names for `pub.layers.media.media`.
pub mod media {
    /// Wire name of the `audio` property.
    pub const AUDIO: &str = "audio";
    /// Wire name of the `blob` property.
    pub const BLOB: &str = "blob";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `document` property.
    pub const DOCUMENT: &str = "document";
    /// Wire name of the `durationMs` property.
    pub const DURATION_MS: &str = "durationMs";
    /// Wire name of the `externalUri` property.
    pub const EXTERNAL_URI: &str = "externalUri";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `fileSizeBytes` property.
    pub const FILE_SIZE_BYTES: &str = "fileSizeBytes";
    /// Wire name of the `kind` property.
    pub const KIND: &str = "kind";
    /// Wire name of the `kindUri` property.
    pub const KIND_URI: &str = "kindUri";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `languages` property.
    pub const LANGUAGES: &str = "languages";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `mimeType` property.
    pub const MIME_TYPE: &str = "mimeType";
    /// Wire name of the `parentMediaRef` property.
    pub const PARENT_MEDIA_REF: &str = "parentMediaRef";
    /// Wire name of the `startOffsetMs` property.
    pub const START_OFFSET_MS: &str = "startOffsetMs";
    /// Wire name of the `title` property.
    pub const TITLE: &str = "title";
    /// Wire name of the `video` property.
    pub const VIDEO: &str = "video";
}

/// Field names for `pub.layers.ontology.ontology`.
pub mod ontology {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `domain` property.
    pub const DOMAIN: &str = "domain";
    /// Wire name of the `domainUri` property.
    pub const DOMAIN_URI: &str = "domainUri";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `name` property.
    pub const NAME: &str = "name";
    /// Wire name of the `parentRef` property.
    pub const PARENT_REF: &str = "parentRef";
    /// Wire name of the `personaRef` property.
    pub const PERSONA_REF: &str = "personaRef";
    /// Wire name of the `version` property.
    pub const VERSION: &str = "version";
}

/// Field names for `pub.layers.persona.persona`.
pub mod persona {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `description` property.
    pub const DESCRIPTION: &str = "description";
    /// Wire name of the `domain` property.
    pub const DOMAIN: &str = "domain";
    /// Wire name of the `domainUri` property.
    pub const DOMAIN_URI: &str = "domainUri";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `guidelines` property.
    pub const GUIDELINES: &str = "guidelines";
    /// Wire name of the `guidelinesBlob` property.
    pub const GUIDELINES_BLOB: &str = "guidelinesBlob";
    /// Wire name of the `guidelinesFormat` property.
    pub const GUIDELINES_FORMAT: &str = "guidelinesFormat";
    /// Wire name of the `kind` property.
    pub const KIND: &str = "kind";
    /// Wire name of the `kindUri` property.
    pub const KIND_URI: &str = "kindUri";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `name` property.
    pub const NAME: &str = "name";
    /// Wire name of the `ontologyRefs` property.
    pub const ONTOLOGY_REFS: &str = "ontologyRefs";
    /// Wire name of the `parentRef` property.
    pub const PARENT_REF: &str = "parentRef";
}

/// Field names for `pub.layers.segmentation.segmentation`.
pub mod segmentation {
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `expression` property.
    pub const EXPRESSION: &str = "expression";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `tokenizations` property.
    pub const TOKENIZATIONS: &str = "tokenizations";
}

/// Field names for `pub.layers.resource.template`.
pub mod template {
    /// Wire name of the `constraints` property.
    pub const CONSTRAINTS: &str = "constraints";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `experimentRef` property.
    pub const EXPERIMENT_REF: &str = "experimentRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `languages` property.
    pub const LANGUAGES: &str = "languages";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
    /// Wire name of the `name` property.
    pub const NAME: &str = "name";
    /// Wire name of the `ontologyRef` property.
    pub const ONTOLOGY_REF: &str = "ontologyRef";
    /// Wire name of the `slots` property.
    pub const SLOTS: &str = "slots";
    /// Wire name of the `text` property.
    pub const TEXT: &str = "text";
}

/// Field names for `pub.layers.resource.templateComposition`.
pub mod template_composition {
    /// Wire name of the `compositionType` property.
    pub const COMPOSITION_TYPE: &str = "compositionType";
    /// Wire name of the `compositionTypeUri` property.
    pub const COMPOSITION_TYPE_URI: &str = "compositionTypeUri";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `experimentRef` property.
    pub const EXPERIMENT_REF: &str = "experimentRef";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `members` property.
    pub const MEMBERS: &str = "members";
    /// Wire name of the `metadata` property.
    pub const METADATA: &str = "metadata";
}

/// Field names for `pub.layers.ontology.typeDef`.
pub mod type_def {
    /// Wire name of the `allowedRoles` property.
    pub const ALLOWED_ROLES: &str = "allowedRoles";
    /// Wire name of the `allowedValues` property.
    pub const ALLOWED_VALUES: &str = "allowedValues";
    /// Wire name of the `createdAt` property.
    pub const CREATED_AT: &str = "createdAt";
    /// Wire name of the `features` property.
    pub const FEATURES: &str = "features";
    /// Wire name of the `gloss` property.
    pub const GLOSS: &str = "gloss";
    /// Wire name of the `knowledgeRefs` property.
    pub const KNOWLEDGE_REFS: &str = "knowledgeRefs";
    /// Wire name of the `name` property.
    pub const NAME: &str = "name";
    /// Wire name of the `ontologyRef` property.
    pub const ONTOLOGY_REF: &str = "ontologyRef";
    /// Wire name of the `parentTypeRef` property.
    pub const PARENT_TYPE_REF: &str = "parentTypeRef";
    /// Wire name of the `typeKind` property.
    pub const TYPE_KIND: &str = "typeKind";
    /// Wire name of the `typeKindUri` property.
    pub const TYPE_KIND_URI: &str = "typeKindUri";
}
