// @generated by layers-codegen. do not edit.

//! NSID -> Postgres table map for every `pub.layers.*` record kind.
//!
//! Generated from `crates/layers-codegen/src/tables.rs`, which is also
//! read by the orchestrator route generator, so the runtime sink and
//! the generated query handlers can never disagree on table names.

/// Every record kind's `(nsid, table)`, sorted by NSID.
pub const TABLES: &[(&str, &str)] = &[
    ("pub.layers.alignment.alignment", "alignments"),
    ("pub.layers.annotation.annotationLayer", "annotation_layers"),
    ("pub.layers.annotation.clusterSet", "cluster_sets"),
    ("pub.layers.changelog.entry", "changelog_entries"),
    ("pub.layers.corpus.corpus", "corpora"),
    ("pub.layers.corpus.membership", "corpus_memberships"),
    ("pub.layers.eprint.dataLink", "data_links"),
    ("pub.layers.eprint.eprint", "eprints"),
    ("pub.layers.expression.expression", "expressions"),
    ("pub.layers.graph.graphEdge", "graph_edges"),
    ("pub.layers.graph.graphEdgeSet", "graph_edge_sets"),
    ("pub.layers.graph.graphNode", "graph_nodes"),
    ("pub.layers.judgment.agreementReport", "agreement_reports"),
    ("pub.layers.judgment.experimentDef", "experiment_defs"),
    ("pub.layers.judgment.judgmentSet", "judgment_sets"),
    ("pub.layers.media.media", "media_records"),
    ("pub.layers.ontology.ontology", "ontologies"),
    ("pub.layers.ontology.typeDef", "type_defs"),
    ("pub.layers.persona.persona", "personas"),
    ("pub.layers.resource.collection", "resource_collections"),
    (
        "pub.layers.resource.collectionMembership",
        "resource_collection_memberships",
    ),
    ("pub.layers.resource.entry", "resource_entries"),
    ("pub.layers.resource.filling", "resource_fillings"),
    ("pub.layers.resource.template", "resource_templates"),
    (
        "pub.layers.resource.templateComposition",
        "resource_template_compositions",
    ),
    ("pub.layers.segmentation.segmentation", "segmentations"),
];

/// Postgres table for a record NSID, or `None` when the NSID is not a
/// known `pub.layers.*` record kind.
#[must_use]
pub fn table_for(nsid: &str) -> Option<&'static str> {
    TABLES
        .iter()
        .copied()
        .find(|(n, _)| *n == nsid)
        .map(|(_, t)| t)
}
