#!/usr/bin/env node
// Emit CREATE TABLE migrations for every record kind from its lens spec.
// The lens's `extensions.storage.columns` block is the single source of truth
// for the column list + Postgres types. Output goes to
// layers/migrations/generated/001_lens_schema.sql (one file, idempotent).

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const LENSES_DIR = join(ROOT, 'lenses');
const OUT_DIR = join(ROOT, 'migrations', 'generated');

function pgTypeForExpr(expr) {
  // Infer a sensible Postgres column type from the DSL expression shape.
  switch (expr.kind) {
    case 'uri':
    case 'did':
    case 'rkey':
      return 'text not null';
    case 'now':
      return 'timestamptz not null default now()';
    case 'record-json':
      return 'jsonb not null';
    case 'literal':
      return expr.value === null ? 'text' : typeof expr.value === 'number' ? 'numeric' : 'text';
    case 'field':
      return expr.nullable ? 'text' : 'text not null';
    case 'field-or':
      return 'text';
    case 'field-chain':
      return expr.nullable ? 'text' : 'text not null';
    case 'count':
      return expr.nullable ? 'integer' : 'integer not null';
    case 'json-stringify-field':
      return 'jsonb';
    case 'raw':
      return 'text';
    default:
      return 'text';
  }
}

function emitTableDdl(spec) {
  const cols = [];
  // uri/did/rkey/indexed_at/record are always present.
  cols.push('uri text primary key');
  cols.push('did text not null');
  cols.push('rkey text not null');
  cols.push('indexed_at timestamptz not null default now()');
  cols.push('record jsonb not null');

  const businessCols = Object.entries(spec.columns).filter(
    ([name]) => !['uri', 'did', 'rkey', 'indexed_at', 'record'].includes(name),
  );
  for (const [name, expr] of businessCols) {
    cols.push(`${name} ${pgTypeForExpr(expr)}`);
  }

  const table = spec.table;
  const ddl = `-- ${spec.collection}\ncreate table if not exists ${table} (\n  ${cols.join(',\n  ')}\n);\ncreate index if not exists ${table}_did_idx on ${table} (did);\ncreate index if not exists ${table}_indexed_at_idx on ${table} (indexed_at);\n`;
  return ddl;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const parts = ['-- Generated by layers/codegen/emit-sql.mjs -- do not edit.\n'];
  for (const file of readdirSync(LENSES_DIR).sort()) {
    if (!file.endsWith('.lens.json')) continue;
    const lens = JSON.parse(readFileSync(join(LENSES_DIR, file), 'utf8'));
    const spec = lens.extensions?.storage;
    if (!spec?.table) continue;
    parts.push(emitTableDdl(spec));
  }
  const outPath = join(OUT_DIR, '001_lens_schema.sql');
  writeFileSync(outPath, parts.join('\n'));
  console.log(`  wrote ${parts.length - 1} table DDLs -> ${relative(ROOT, outPath)}`);
}

main();
