// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.judgment.agreementReport

import { z } from 'zod';

const getAgreementReportParamsSchema = z.object({
  uri: z.string().min(1),
});

const listAgreementReportsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const agreementReportRecordSchema = z.object({
  "experimentRef": z.string(),
  "judgmentSetRefs": z.array(z.string()).optional(),
  "metricUri": z.string().optional(),
  "metric": z.string().max(128).optional(),
  "value": z.number().int().min(0).max(1000).optional(),
  "numAnnotators": z.number().int().min(1).optional(),
  "numItems": z.number().int().min(1).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type AgreementReportRecord = z.infer<typeof agreementReportRecordSchema>;

interface AgreementReportRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly experiment_ref: string;
  readonly metric: string | null;
  readonly score: number | null;
  readonly indexed_at: Date;
  readonly record: AgreementReportRecord;
}

interface AgreementReportView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly experimentRef: string;
  readonly metric: string | null;
  readonly score: number | null;
  readonly indexedAt: string;
  readonly record: AgreementReportRecord;
}

function toAgreementReportView(row: AgreementReportRow): AgreementReportView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    experimentRef: row.experiment_ref,
    metric: row.metric,
    score: row.score,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  agreementReportRecordSchema,
  getAgreementReportParamsSchema,
  listAgreementReportsParamsSchema,
  toAgreementReportView,
};
export type { AgreementReportRecord, AgreementReportRow, AgreementReportView };
