// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.alignment.alignment

import { z } from 'zod';

const getAlignmentParamsSchema = z.object({
  uri: z.string().min(1),
});

const listAlignmentsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const alignmentRecordSchema = z.object({
  "expression": z.string().optional(),
  "kindUri": z.string().optional(),
  "kind": z.string().max(128),
  "subkindUri": z.string().optional(),
  "subkind": z.string().max(128).optional(),
  "source": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "target": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "sourceLang": z.string().max(64).optional(),
  "targetLang": z.string().max(64).optional(),
  "links": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(16).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type AlignmentRecord = z.infer<typeof alignmentRecordSchema>;

interface AlignmentRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expression_ref: string | null;
  readonly source_ref: string;
  readonly target_ref: string;
  readonly kind: string;
  readonly subkind: string | null;
  readonly indexed_at: Date;
  readonly record: AlignmentRecord;
}

interface AlignmentView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expressionRef: string | null;
  readonly sourceRef: string;
  readonly targetRef: string;
  readonly kind: string;
  readonly subkind: string | null;
  readonly indexedAt: string;
  readonly record: AlignmentRecord;
}

function toAlignmentView(row: AlignmentRow): AlignmentView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    expressionRef: row.expression_ref,
    sourceRef: row.source_ref,
    targetRef: row.target_ref,
    kind: row.kind,
    subkind: row.subkind,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  alignmentRecordSchema,
  getAlignmentParamsSchema,
  listAlignmentsParamsSchema,
  toAlignmentView,
};
export type { AlignmentRecord, AlignmentRow, AlignmentView };
