// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.annotation.annotationLayer

import { z } from 'zod';

const getAnnotationLayerParamsSchema = z.object({
  uri: z.string().min(1),
});

const listAnnotationLayersParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const annotationLayerRecordSchema = z.object({
  "expression": z.string(),
  "kindUri": z.string().optional(),
  "kind": z.string().max(128),
  "subkindUri": z.string().optional(),
  "subkind": z.string().max(128).optional(),
  "formalismUri": z.string().optional(),
  "formalism": z.string().max(128).optional(),
  "sourceMethodUri": z.string().optional(),
  "sourceMethod": z.string().max(128).optional(),
  "labelSet": z.string().max(256).optional(),
  "ontologyRef": z.string().optional(),
  "tokenizationId": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "rank": z.number().int().min(1).optional(),
  "alternativesRef": z.string().optional(),
  "parentLayerRef": z.string().optional(),
  "language": z.string().max(64).optional(),
  "annotations": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type AnnotationLayerRecord = z.infer<typeof annotationLayerRecordSchema>;

interface AnnotationLayerRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expression_ref: string;
  readonly segmentation_ref: string | null;
  readonly kind: string;
  readonly subkind: string | null;
  readonly formalism: string | null;
  readonly ontology_ref: string | null;
  readonly persona_ref: string | null;
  readonly annotation_count: number;
  readonly indexed_at: Date;
  readonly record: AnnotationLayerRecord;
}

interface AnnotationLayerView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expressionRef: string;
  readonly segmentationRef: string | null;
  readonly kind: string;
  readonly subkind: string | null;
  readonly formalism: string | null;
  readonly ontologyRef: string | null;
  readonly personaRef: string | null;
  readonly annotationCount: number;
  readonly indexedAt: string;
  readonly record: AnnotationLayerRecord;
}

function toAnnotationLayerView(row: AnnotationLayerRow): AnnotationLayerView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    expressionRef: row.expression_ref,
    segmentationRef: row.segmentation_ref,
    kind: row.kind,
    subkind: row.subkind,
    formalism: row.formalism,
    ontologyRef: row.ontology_ref,
    personaRef: row.persona_ref,
    annotationCount: row.annotation_count,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  annotationLayerRecordSchema,
  getAnnotationLayerParamsSchema,
  listAnnotationLayersParamsSchema,
  toAnnotationLayerView,
};
export type { AnnotationLayerRecord, AnnotationLayerRow, AnnotationLayerView };
