// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.changelog.entry

import { z } from 'zod';

const getChangelogEntryParamsSchema = z.object({
  uri: z.string().min(1),
});

const listChangelogEntriesParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchChangelogEntriesParamsSchema = z.object({
  q: z.string().min(1),
  subjectCollection: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const changelogEntryRecordSchema = z.object({
  "subject": z.string(),
  "subjectCollection": z.string().max(256),
  "version": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "previousVersion": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "summary": z.string().max(500),
  "sections": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(20),
  "createdAt": z.string(),
});

type ChangelogEntryRecord = z.infer<typeof changelogEntryRecordSchema>;

interface ChangelogEntryRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly subject_uri: string;
  readonly subject_collection: string;
  readonly summary: string;
  readonly indexed_at: Date;
  readonly record: ChangelogEntryRecord;
}

interface ChangelogEntryView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly subjectUri: string;
  readonly subjectCollection: string;
  readonly summary: string;
  readonly indexedAt: string;
  readonly record: ChangelogEntryRecord;
}

function toChangelogEntryView(row: ChangelogEntryRow): ChangelogEntryView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    subjectUri: row.subject_uri,
    subjectCollection: row.subject_collection,
    summary: row.summary,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  changelogEntryRecordSchema,
  getChangelogEntryParamsSchema,
  listChangelogEntriesParamsSchema,
  searchChangelogEntriesParamsSchema,
  toChangelogEntryView,
};
export type { ChangelogEntryRecord, ChangelogEntryRow, ChangelogEntryView };
