// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.annotation.clusterSet

import { z } from 'zod';

const getClusterSetParamsSchema = z.object({
  uri: z.string().min(1),
});

const listClusterSetsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const clusterSetRecordSchema = z.object({
  "expression": z.string().optional(),
  "expressionRefs": z.array(z.string()).max(10000).optional(),
  "corpusRef": z.string().optional(),
  "kindUri": z.string().optional(),
  "kind": z.string().max(128),
  "layerRef": z.string().optional(),
  "clusters": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type ClusterSetRecord = z.infer<typeof clusterSetRecordSchema>;

interface ClusterSetRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expression_ref: string | null;
  readonly layer_ref: string;
  readonly kind: string | null;
  readonly indexed_at: Date;
  readonly record: ClusterSetRecord;
}

interface ClusterSetView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expressionRef: string | null;
  readonly layerRef: string;
  readonly kind: string | null;
  readonly indexedAt: string;
  readonly record: ClusterSetRecord;
}

function toClusterSetView(row: ClusterSetRow): ClusterSetView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    expressionRef: row.expression_ref,
    layerRef: row.layer_ref,
    kind: row.kind,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  clusterSetRecordSchema,
  getClusterSetParamsSchema,
  listClusterSetsParamsSchema,
  toClusterSetView,
};
export type { ClusterSetRecord, ClusterSetRow, ClusterSetView };
