// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.resource.collectionMembership

import { z } from 'zod';

const getCollectionMembershipParamsSchema = z.object({
  uri: z.string().min(1),
});

const listCollectionMembershipsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const collectionMembershipRecordSchema = z.object({
  "collectionRef": z.string(),
  "entryRef": z.string(),
  "ordinal": z.number().int().min(0).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type CollectionMembershipRecord = z.infer<typeof collectionMembershipRecordSchema>;

interface CollectionMembershipRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly collection_ref: string;
  readonly entry_ref: string;
  readonly ordinal: number | null;
  readonly indexed_at: Date;
  readonly record: CollectionMembershipRecord;
}

interface CollectionMembershipView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly collectionRef: string;
  readonly entryRef: string;
  readonly ordinal: number | null;
  readonly indexedAt: string;
  readonly record: CollectionMembershipRecord;
}

function toCollectionMembershipView(row: CollectionMembershipRow): CollectionMembershipView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    collectionRef: row.collection_ref,
    entryRef: row.entry_ref,
    ordinal: row.ordinal,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  collectionMembershipRecordSchema,
  getCollectionMembershipParamsSchema,
  listCollectionMembershipsParamsSchema,
  toCollectionMembershipView,
};
export type { CollectionMembershipRecord, CollectionMembershipRow, CollectionMembershipView };
