// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.corpus.corpus

import { z } from 'zod';

const getCorpusParamsSchema = z.object({
  uri: z.string().min(1),
});

const listCorporaParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchCorporaParamsSchema = z.object({
  q: z.string().min(1),
  language: z.string().optional(),
  domain: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const corpusRecordSchema = z.object({
  "name": z.string().max(512),
  "description": z.string().max(50000).optional(),
  "version": z.string().max(64).optional(),
  "language": z.string().max(32).optional(),
  "languages": z.array(z.string().max(32)).max(128).optional(),
  "domainUri": z.string().optional(),
  "domain": z.string().max(256).optional(),
  "license": z.string().max(256).optional(),
  "ontologyRefs": z.array(z.string()).max(32).optional(),
  "eprintRefs": z.array(z.string()).max(64).optional(),
  "expressionCount": z.number().int().min(0).optional(),
  "annotationDesign": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type CorpusRecord = z.infer<typeof corpusRecordSchema>;

interface CorpusRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly language: string | null;
  readonly license: string | null;
  readonly domain: string | null;
  readonly indexed_at: Date;
  readonly record: CorpusRecord;
}

interface CorpusView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly language: string | null;
  readonly license: string | null;
  readonly domain: string | null;
  readonly indexedAt: string;
  readonly record: CorpusRecord;
}

function toCorpusView(row: CorpusRow): CorpusView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    name: row.name,
    language: row.language,
    license: row.license,
    domain: row.domain,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  corpusRecordSchema,
  getCorpusParamsSchema,
  listCorporaParamsSchema,
  searchCorporaParamsSchema,
  toCorpusView,
};
export type { CorpusRecord, CorpusRow, CorpusView };
