// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.corpus.membership

import { z } from 'zod';

const getMembershipParamsSchema = z.object({
  uri: z.string().min(1),
});

const listMembershipsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const corpusMembershipRecordSchema = z.object({
  "corpusRef": z.string(),
  "expressionRef": z.string(),
  "splitUri": z.string().optional(),
  "split": z.string().max(64).optional(),
  "ordinal": z.number().int().min(0).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type CorpusMembershipRecord = z.infer<typeof corpusMembershipRecordSchema>;

interface CorpusMembershipRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly corpus_ref: string;
  readonly expression_ref: string;
  readonly split: string | null;
  readonly indexed_at: Date;
  readonly record: CorpusMembershipRecord;
}

interface CorpusMembershipView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly corpusRef: string;
  readonly expressionRef: string;
  readonly split: string | null;
  readonly indexedAt: string;
  readonly record: CorpusMembershipRecord;
}

function toCorpusMembershipView(row: CorpusMembershipRow): CorpusMembershipView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    corpusRef: row.corpus_ref,
    expressionRef: row.expression_ref,
    split: row.split,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  corpusMembershipRecordSchema,
  getMembershipParamsSchema,
  listMembershipsParamsSchema,
  toCorpusMembershipView,
};
export type { CorpusMembershipRecord, CorpusMembershipRow, CorpusMembershipView };
