// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.eprint.dataLink

import { z } from 'zod';

const getDataLinkParamsSchema = z.object({
  uri: z.string().min(1),
});

const listDataLinksParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const dataLinkRecordSchema = z.object({
  "eprintUri": z.string(),
  "eprintDid": z.string().optional(),
  "dataKindUri": z.string().optional(),
  "dataKind": z.string().max(128),
  "corpusRef": z.string().optional(),
  "expressionRefs": z.array(z.string()).max(10000).optional(),
  "annotationRefs": z.array(z.string()).max(10000).optional(),
  "description": z.string().max(10000).optional(),
  "paperSection": z.string().max(256).optional(),
  "reproducibility": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type DataLinkRecord = z.infer<typeof dataLinkRecordSchema>;

interface DataLinkRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly eprint_ref: string;
  readonly corpus_ref: string | null;
  readonly link_type: string | null;
  readonly indexed_at: Date;
  readonly record: DataLinkRecord;
}

interface DataLinkView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly eprintRef: string;
  readonly corpusRef: string | null;
  readonly linkType: string | null;
  readonly indexedAt: string;
  readonly record: DataLinkRecord;
}

function toDataLinkView(row: DataLinkRow): DataLinkView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    eprintRef: row.eprint_ref,
    corpusRef: row.corpus_ref,
    linkType: row.link_type,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  dataLinkRecordSchema,
  getDataLinkParamsSchema,
  listDataLinksParamsSchema,
  toDataLinkView,
};
export type { DataLinkRecord, DataLinkRow, DataLinkView };
