// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.eprint.eprint

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getEprintParamsSchema = z.object({
  uri: z.string().min(1),
});

const listEprintsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchEprintsParamsSchema = z.object({
  q: z.string().min(1),
  identifierType: z.string().optional(),
  linkType: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const eprintRecordSchema = z.object({
  "eprintIdentifier": z.string().max(512),
  "eprintIdentifierTypeUri": z.string().optional(),
  "eprintIdentifierType": z.string().max(128).optional(),
  "eprintUri": z.string().optional(),
  "platformEprintRef": z.string().optional(),
  "linkTypeUri": z.string().optional(),
  "linkType": z.string().max(128),
  "expressionRefs": z.array(z.string()).max(1000).optional(),
  "annotationRefs": z.array(z.string()).max(1000).optional(),
  "corpusRef": z.string().optional(),
  "description": z.string().max(10000).optional(),
  "citation": z.string().max(4096).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type EprintRecord = z.infer<typeof eprintRecordSchema>;

interface EprintRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly eprint_identifier: string;
  readonly eprint_identifier_type: string | null;
  readonly link_type: string;
  readonly corpus_ref: string | null;
  readonly indexed_at: Date;
  readonly record: EprintRecord;
}

interface EprintView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly eprintIdentifier: string;
  readonly eprintIdentifierType: string | null;
  readonly linkType: string;
  readonly corpusRef: string | null;
  readonly indexedAt: string;
  readonly record: EprintRecord;
}

function toEprintView(row: EprintRow): EprintView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    eprintIdentifier: row.eprint_identifier,
    eprintIdentifierType: row.eprint_identifier_type,
    linkType: row.link_type,
    corpusRef: row.corpus_ref,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  eprintRecordSchema,
  knowledgeRefSchema,
  getEprintParamsSchema,
  listEprintsParamsSchema,
  searchEprintsParamsSchema,
  toEprintView,
};
export type { EprintRecord, EprintRow, EprintView };
