// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.expression.expression

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getExpressionParamsSchema = z.object({
  uri: z.string().min(1),
});

const listExpressionsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const searchExpressionsParamsSchema = z.object({
  q: z.string().min(1),
  language: z.string().optional(),
  kind: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const expressionRecordSchema = z.object({
  "id": z.string().max(1024),
  "kindUri": z.string().optional(),
  "kind": z.string().max(128),
  "text": z.string().max(10000000).optional(),
  "parentRef": z.string().optional(),
  "anchor": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "mediaRef": z.string().optional(),
  "mediaBlob": z.unknown().optional(),
  "language": z.string().max(32).optional(),
  "languages": z.array(z.string().max(32)).max(64).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "sourceUrl": z.string().max(4096).optional(),
  "sourceRef": z.string().optional(),
  "eprintRef": z.string().optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(128).optional(),
  "createdAt": z.string(),
});

type ExpressionRecord = z.infer<typeof expressionRecordSchema>;

interface ExpressionRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly text: string | null;
  readonly kind: string | null;
  readonly language: string | null;
  readonly source_url: string | null;
  readonly source_ref: string | null;
  readonly eprint_ref: string | null;
  readonly parent_ref: string | null;
  readonly indexed_at: Date;
  readonly record: ExpressionRecord;
}

interface ExpressionView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly text: string | null;
  readonly kind: string | null;
  readonly language: string | null;
  readonly sourceUrl: string | null;
  readonly sourceRef: string | null;
  readonly eprintRef: string | null;
  readonly parentRef: string | null;
  readonly indexedAt: string;
  readonly record: ExpressionRecord;
}

function toExpressionView(row: ExpressionRow): ExpressionView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    text: row.text,
    kind: row.kind,
    language: row.language,
    sourceUrl: row.source_url,
    sourceRef: row.source_ref,
    eprintRef: row.eprint_ref,
    parentRef: row.parent_ref,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  expressionRecordSchema,
  knowledgeRefSchema,
  getExpressionParamsSchema,
  listExpressionsParamsSchema,
  searchExpressionsParamsSchema,
  toExpressionView,
};
export type { ExpressionRecord, ExpressionRow, ExpressionView };
