// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.resource.filling

import { z } from 'zod';

const getFillingParamsSchema = z.object({
  uri: z.string().min(1),
});

const listFillingsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const fillingRecordSchema = z.object({
  "templateRef": z.string(),
  "slotFillings": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(64),
  "renderedText": z.string().max(100000).optional(),
  "expressionRef": z.string().optional(),
  "strategyUri": z.string().optional(),
  "strategy": z.string().max(128).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type FillingRecord = z.infer<typeof fillingRecordSchema>;

interface FillingRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly template_ref: string;
  readonly expression_ref: string | null;
  readonly strategy: string | null;
  readonly indexed_at: Date;
  readonly record: FillingRecord;
}

interface FillingView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly templateRef: string;
  readonly expressionRef: string | null;
  readonly strategy: string | null;
  readonly indexedAt: string;
  readonly record: FillingRecord;
}

function toFillingView(row: FillingRow): FillingView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    templateRef: row.template_ref,
    expressionRef: row.expression_ref,
    strategy: row.strategy,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  fillingRecordSchema,
  getFillingParamsSchema,
  listFillingsParamsSchema,
  toFillingView,
};
export type { FillingRecord, FillingRow, FillingView };
