// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.graph.graphEdge

import { z } from 'zod';

const getGraphEdgeParamsSchema = z.object({
  uri: z.string().min(1),
});

const listGraphEdgesParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const graphEdgeRecordSchema = z.object({
  "source": z.union([z.string(), z.record(z.string(), z.unknown())]),
  "target": z.union([z.string(), z.record(z.string(), z.unknown())]),
  "edgeTypeUri": z.string().optional(),
  "edgeType": z.string().max(128),
  "label": z.string().max(512).optional(),
  "ordinal": z.number().int().min(0).optional(),
  "confidence": z.number().int().min(0).max(1000).optional(),
  "properties": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type GraphEdgeRecord = z.infer<typeof graphEdgeRecordSchema>;

interface GraphEdgeRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly source_ref: string;
  readonly target_ref: string;
  readonly edge_type: string;
  readonly edge_set_ref: string | null;
  readonly confidence: number | null;
  readonly indexed_at: Date;
  readonly record: GraphEdgeRecord;
}

interface GraphEdgeView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly sourceRef: string;
  readonly targetRef: string;
  readonly edgeType: string;
  readonly edgeSetRef: string | null;
  readonly confidence: number | null;
  readonly indexedAt: string;
  readonly record: GraphEdgeRecord;
}

function toGraphEdgeView(row: GraphEdgeRow): GraphEdgeView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    sourceRef: row.source_ref,
    targetRef: row.target_ref,
    edgeType: row.edge_type,
    edgeSetRef: row.edge_set_ref,
    confidence: row.confidence,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  graphEdgeRecordSchema,
  getGraphEdgeParamsSchema,
  listGraphEdgesParamsSchema,
  toGraphEdgeView,
};
export type { GraphEdgeRecord, GraphEdgeRow, GraphEdgeView };
