// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.graph.graphNode

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getGraphNodeParamsSchema = z.object({
  uri: z.string().min(1),
});

const listGraphNodesParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchGraphNodesParamsSchema = z.object({
  q: z.string().min(1),
  nodeType: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const graphNodeRecordSchema = z.object({
  "nodeTypeUri": z.string().optional(),
  "nodeType": z.string().max(128),
  "label": z.string().max(1024).optional(),
  "properties": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(64).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type GraphNodeRecord = z.infer<typeof graphNodeRecordSchema>;

interface GraphNodeRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly node_type: string;
  readonly label: string | null;
  readonly indexed_at: Date;
  readonly record: GraphNodeRecord;
}

interface GraphNodeView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly nodeType: string;
  readonly label: string | null;
  readonly indexedAt: string;
  readonly record: GraphNodeRecord;
}

function toGraphNodeView(row: GraphNodeRow): GraphNodeView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    nodeType: row.node_type,
    label: row.label,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  graphNodeRecordSchema,
  knowledgeRefSchema,
  getGraphNodeParamsSchema,
  listGraphNodesParamsSchema,
  searchGraphNodesParamsSchema,
  toGraphNodeView,
};
export type { GraphNodeRecord, GraphNodeRow, GraphNodeView };
