// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.graph.graphEdgeSet

import { z } from 'zod';

const getGraphEdgeSetParamsSchema = z.object({
  uri: z.string().min(1),
});

const listGraphEdgeSetsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const graphEdgeSetRecordSchema = z.object({
  "expression": z.string().optional(),
  "edgeTypeUri": z.string().optional(),
  "edgeType": z.string().max(128).optional(),
  "edges": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type GraphEdgeSetRecord = z.infer<typeof graphEdgeSetRecordSchema>;

interface GraphEdgeSetRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string | null;
  readonly edge_type: string;
  readonly edge_count: number | null;
  readonly expression_ref: string | null;
  readonly indexed_at: Date;
  readonly record: GraphEdgeSetRecord;
}

interface GraphEdgeSetView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string | null;
  readonly edgeType: string;
  readonly edgeCount: number | null;
  readonly expressionRef: string | null;
  readonly indexedAt: string;
  readonly record: GraphEdgeSetRecord;
}

function toGraphEdgeSetView(row: GraphEdgeSetRow): GraphEdgeSetView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    name: row.name,
    edgeType: row.edge_type,
    edgeCount: row.edge_count,
    expressionRef: row.expression_ref,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  graphEdgeSetRecordSchema,
  getGraphEdgeSetParamsSchema,
  listGraphEdgeSetsParamsSchema,
  toGraphEdgeSetView,
};
export type { GraphEdgeSetRecord, GraphEdgeSetRow, GraphEdgeSetView };
