// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.judgment.judgmentSet

import { z } from 'zod';

const getJudgmentSetParamsSchema = z.object({
  uri: z.string().min(1),
});

const listJudgmentSetsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const judgmentSetRecordSchema = z.object({
  "experimentRef": z.string(),
  "agent": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "judgments": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type JudgmentSetRecord = z.infer<typeof judgmentSetRecordSchema>;

interface JudgmentSetRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly experiment_ref: string;
  readonly annotator_did: string | null;
  readonly indexed_at: Date;
  readonly record: JudgmentSetRecord;
}

interface JudgmentSetView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly experimentRef: string;
  readonly annotatorDid: string | null;
  readonly indexedAt: string;
  readonly record: JudgmentSetRecord;
}

function toJudgmentSetView(row: JudgmentSetRow): JudgmentSetView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    experimentRef: row.experiment_ref,
    annotatorDid: row.annotator_did,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  judgmentSetRecordSchema,
  getJudgmentSetParamsSchema,
  listJudgmentSetsParamsSchema,
  toJudgmentSetView,
};
export type { JudgmentSetRecord, JudgmentSetRow, JudgmentSetView };
