// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.media.media

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getMediaParamsSchema = z.object({
  uri: z.string().min(1),
});

const listMediaParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchMediaParamsSchema = z.object({
  q: z.string().min(1),
  kind: z.string().optional(),
  language: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const mediaRecordSchema = z.object({
  "kindUri": z.string().optional(),
  "kind": z.string().max(128),
  "title": z.string().max(1024).optional(),
  "description": z.string().max(10000).optional(),
  "blob": z.unknown().optional(),
  "externalUri": z.string().max(2048).optional(),
  "mimeType": z.string().max(128).optional(),
  "durationMs": z.number().int().min(0).optional(),
  "fileSizeBytes": z.number().int().min(0).optional(),
  "parentMediaRef": z.string().optional(),
  "startOffsetMs": z.number().int().min(0).optional(),
  "audio": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "video": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "document": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "language": z.string().max(32).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type MediaRecord = z.infer<typeof mediaRecordSchema>;

interface MediaRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly kind: string;
  readonly mime_type: string | null;
  readonly duration_ms: number | null;
  readonly language: string | null;
  readonly indexed_at: Date;
  readonly record: MediaRecord;
}

interface MediaView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly kind: string;
  readonly mimeType: string | null;
  readonly durationMs: number | null;
  readonly language: string | null;
  readonly indexedAt: string;
  readonly record: MediaRecord;
}

function toMediaView(row: MediaRow): MediaView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    kind: row.kind,
    mimeType: row.mime_type,
    durationMs: row.duration_ms,
    language: row.language,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  mediaRecordSchema,
  knowledgeRefSchema,
  getMediaParamsSchema,
  listMediaParamsSchema,
  searchMediaParamsSchema,
  toMediaView,
};
export type { MediaRecord, MediaRow, MediaView };
