// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.ontology.ontology

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getOntologyParamsSchema = z.object({
  uri: z.string().min(1),
});

const listOntologiesParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchOntologiesParamsSchema = z.object({
  q: z.string().min(1),
  domain: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const ontologyRecordSchema = z.object({
  "name": z.string().max(512),
  "description": z.string().max(10000).optional(),
  "version": z.string().max(32).optional(),
  "domainUri": z.string().optional(),
  "domain": z.string().max(128).optional(),
  "parentRef": z.string().optional(),
  "personaRef": z.string().optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(64).optional(),
  "createdAt": z.string(),
});

type OntologyRecord = z.infer<typeof ontologyRecordSchema>;

interface OntologyRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly domain: string | null;
  readonly version: string | null;
  readonly indexed_at: Date;
  readonly record: OntologyRecord;
}

interface OntologyView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly domain: string | null;
  readonly version: string | null;
  readonly indexedAt: string;
  readonly record: OntologyRecord;
}

function toOntologyView(row: OntologyRow): OntologyView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    name: row.name,
    domain: row.domain,
    version: row.version,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  ontologyRecordSchema,
  knowledgeRefSchema,
  getOntologyParamsSchema,
  listOntologiesParamsSchema,
  searchOntologiesParamsSchema,
  toOntologyView,
};
export type { OntologyRecord, OntologyRow, OntologyView };
