// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.persona.persona

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getPersonaParamsSchema = z.object({
  uri: z.string().min(1),
});

const listPersonasParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchPersonasParamsSchema = z.object({
  q: z.string().min(1),
  domain: z.string().optional(),
  kind: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const personaRecordSchema = z.object({
  "name": z.string().max(256),
  "description": z.string().max(10000).optional(),
  "domainUri": z.string().optional(),
  "domain": z.string().max(256).optional(),
  "kindUri": z.string().optional(),
  "kind": z.string().max(128).optional(),
  "parentRef": z.string().optional(),
  "ontologyRefs": z.array(z.string()).max(32).optional(),
  "guidelines": z.string().max(100000).optional(),
  "guidelinesBlob": z.unknown().optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type PersonaRecord = z.infer<typeof personaRecordSchema>;

interface PersonaRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly domain: string | null;
  readonly kind: string | null;
  readonly indexed_at: Date;
  readonly record: PersonaRecord;
}

interface PersonaView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly domain: string | null;
  readonly kind: string | null;
  readonly indexedAt: string;
  readonly record: PersonaRecord;
}

function toPersonaView(row: PersonaRow): PersonaView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    name: row.name,
    domain: row.domain,
    kind: row.kind,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  personaRecordSchema,
  knowledgeRefSchema,
  getPersonaParamsSchema,
  listPersonasParamsSchema,
  searchPersonasParamsSchema,
  toPersonaView,
};
export type { PersonaRecord, PersonaRow, PersonaView };
