// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.resource.collection

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getCollectionParamsSchema = z.object({
  uri: z.string().min(1),
});

const listCollectionsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchCollectionsParamsSchema = z.object({
  q: z.string().min(1),
  kind: z.string().optional(),
  language: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const resourceCollectionRecordSchema = z.object({
  "name": z.string().max(512),
  "description": z.string().max(10000).optional(),
  "kindUri": z.string().optional(),
  "kind": z.string().max(128).optional(),
  "language": z.string().max(32).optional(),
  "version": z.string().max(64).optional(),
  "ontologyRef": z.string().optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type ResourceCollectionRecord = z.infer<typeof resourceCollectionRecordSchema>;

interface ResourceCollectionRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly kind: string | null;
  readonly language: string | null;
  readonly indexed_at: Date;
  readonly record: ResourceCollectionRecord;
}

interface ResourceCollectionView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly kind: string | null;
  readonly language: string | null;
  readonly indexedAt: string;
  readonly record: ResourceCollectionRecord;
}

function toResourceCollectionView(row: ResourceCollectionRow): ResourceCollectionView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    name: row.name,
    kind: row.kind,
    language: row.language,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  resourceCollectionRecordSchema,
  knowledgeRefSchema,
  getCollectionParamsSchema,
  listCollectionsParamsSchema,
  searchCollectionsParamsSchema,
  toResourceCollectionView,
};
export type { ResourceCollectionRecord, ResourceCollectionRow, ResourceCollectionView };
