// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.resource.entry

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getEntryParamsSchema = z.object({
  uri: z.string().min(1),
});

const listEntriesParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchEntriesParamsSchema = z.object({
  q: z.string().min(1),
  language: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const resourceEntryRecordSchema = z.object({
  "lemma": z.string().max(1024).optional(),
  "form": z.string().max(4096),
  "language": z.string().max(32).optional(),
  "ontologyTypeRef": z.string().optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "components": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "mweKindUri": z.string().optional(),
  "mweKind": z.string().max(128).optional(),
  "sourceRef": z.string().optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type ResourceEntryRecord = z.infer<typeof resourceEntryRecordSchema>;

interface ResourceEntryRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly form: string;
  readonly lemma: string | null;
  readonly language: string | null;
  readonly indexed_at: Date;
  readonly record: ResourceEntryRecord;
}

interface ResourceEntryView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly form: string;
  readonly lemma: string | null;
  readonly language: string | null;
  readonly indexedAt: string;
  readonly record: ResourceEntryRecord;
}

function toResourceEntryView(row: ResourceEntryRow): ResourceEntryView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    form: row.form,
    lemma: row.lemma,
    language: row.language,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  resourceEntryRecordSchema,
  knowledgeRefSchema,
  getEntryParamsSchema,
  listEntriesParamsSchema,
  searchEntriesParamsSchema,
  toResourceEntryView,
};
export type { ResourceEntryRecord, ResourceEntryRow, ResourceEntryView };
