// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.segmentation.segmentation

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getSegmentationParamsSchema = z.object({
  uri: z.string().min(1),
});

const listSegmentationsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const segmentationRecordSchema = z.object({
  "expression": z.string(),
  "tokenizations": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(16).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type SegmentationRecord = z.infer<typeof segmentationRecordSchema>;

interface SegmentationRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expression_ref: string;
  readonly indexed_at: Date;
  readonly record: SegmentationRecord;
}

interface SegmentationView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly expressionRef: string;
  readonly indexedAt: string;
  readonly record: SegmentationRecord;
}

function toSegmentationView(row: SegmentationRow): SegmentationView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    expressionRef: row.expression_ref,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  segmentationRecordSchema,
  knowledgeRefSchema,
  getSegmentationParamsSchema,
  listSegmentationsParamsSchema,
  toSegmentationView,
};
export type { SegmentationRecord, SegmentationRow, SegmentationView };
