// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.resource.template

import { z } from 'zod';

const getTemplateParamsSchema = z.object({
  uri: z.string().min(1),
});

const listTemplatesParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const templateRecordSchema = z.object({
  "name": z.string().max(512).optional(),
  "text": z.string().max(50000),
  "language": z.string().max(32).optional(),
  "slots": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(64),
  "constraints": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(64).optional(),
  "ontologyRef": z.string().optional(),
  "experimentRef": z.string().optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type TemplateRecord = z.infer<typeof templateRecordSchema>;

interface TemplateRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly slot_count: number | null;
  readonly experiment_ref: string | null;
  readonly language: string | null;
  readonly indexed_at: Date;
  readonly record: TemplateRecord;
}

interface TemplateView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly slotCount: number | null;
  readonly experimentRef: string | null;
  readonly language: string | null;
  readonly indexedAt: string;
  readonly record: TemplateRecord;
}

function toTemplateView(row: TemplateRow): TemplateView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    name: row.name,
    slotCount: row.slot_count,
    experimentRef: row.experiment_ref,
    language: row.language,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  templateRecordSchema,
  getTemplateParamsSchema,
  listTemplatesParamsSchema,
  toTemplateView,
};
export type { TemplateRecord, TemplateRow, TemplateView };
