// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.resource.templateComposition

import { z } from 'zod';

const getTemplateCompositionParamsSchema = z.object({
  uri: z.string().min(1),
});

const listTemplateCompositionsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const templateCompositionRecordSchema = z.object({
  "compositionTypeUri": z.string().optional(),
  "compositionType": z.string().max(128),
  "members": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(256),
  "experimentRef": z.string().optional(),
  "metadata": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type TemplateCompositionRecord = z.infer<typeof templateCompositionRecordSchema>;

interface TemplateCompositionRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly indexed_at: Date;
  readonly record: TemplateCompositionRecord;
}

interface TemplateCompositionView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly name: string;
  readonly indexedAt: string;
  readonly record: TemplateCompositionRecord;
}

function toTemplateCompositionView(row: TemplateCompositionRow): TemplateCompositionView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    name: row.name,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  templateCompositionRecordSchema,
  getTemplateCompositionParamsSchema,
  listTemplateCompositionsParamsSchema,
  toTemplateCompositionView,
};
export type { TemplateCompositionRecord, TemplateCompositionRow, TemplateCompositionView };
