// Generated by layers/codegen/generate.mjs — do not edit by hand.
// Driven by @panproto/core and layers/codegen/record-configs.json.
// Source lexicon: pub.layers.ontology.typeDef

import { z } from 'zod';

const knowledgeRefSchema = z.object({
  source: z.string(),
  identifier: z.string(),
  label: z.string().optional(),
  uri: z.string().optional(),
});

const getTypeDefParamsSchema = z.object({
  uri: z.string().min(1),
});

const listTypeDefsParamsSchema = z.object({
  repo: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.string().optional(),
});

const searchTypeDefsParamsSchema = z.object({
  q: z.string().min(1),
  typeKind: z.string().optional(),
  ontologyRef: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

const typeDefRecordSchema = z.object({
  "ontologyRef": z.string(),
  "name": z.string().max(512),
  "typeKindUri": z.string().optional(),
  "typeKind": z.string().max(128),
  "gloss": z.string().max(10000).optional(),
  "parentTypeRef": z.string().optional(),
  "allowedRoles": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(64).optional(),
  "allowedValues": z.array(z.string().max(512)).max(256).optional(),
  "knowledgeRefs": z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).max(32).optional(),
  "features": z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  "createdAt": z.string(),
});

type TypeDefRecord = z.infer<typeof typeDefRecordSchema>;

interface TypeDefRow {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly ontology_ref: string;
  readonly name: string;
  readonly type_kind: string;
  readonly indexed_at: Date;
  readonly record: TypeDefRecord;
}

interface TypeDefView {
  readonly uri: string;
  readonly did: string;
  readonly rkey: string;
  readonly ontologyRef: string;
  readonly name: string;
  readonly typeKind: string;
  readonly indexedAt: string;
  readonly record: TypeDefRecord;
}

function toTypeDefView(row: TypeDefRow): TypeDefView {
  return {
    uri: row.uri,
    did: row.did,
    rkey: row.rkey,
    ontologyRef: row.ontology_ref,
    name: row.name,
    typeKind: row.type_kind,
    indexedAt: row.indexed_at.toISOString(),
    record: row.record,
  };
}

export {
  typeDefRecordSchema,
  knowledgeRefSchema,
  getTypeDefParamsSchema,
  listTypeDefsParamsSchema,
  searchTypeDefsParamsSchema,
  toTypeDefView,
};
export type { TypeDefRecord, TypeDefRow, TypeDefView };
