//! Emit Zod schemas + field metadata for every `pub.layers.*` record
//! lexicon. The metadata feeds two consumers:
//!
//! - the `<XForm>` scaffolds in `web/components/forms/generated/`,
//!   which a future codegen step renders into typed react-hook-form
//!   surfaces, and
//! - the generic annotation renderer in
//!   `web/components/annotations/generic/` (Phase 4), which falls back
//!   to a labelled key/value display whenever no concrete renderer is
//!   registered for an annotation `(kind, anchor)` cell.
//!
//! Output files (one Zod + one field-metadata file per record
//! lexicon):
//!
//! - `web/lib/forms/generated/<dotted.nsid>.schema.ts`
//! - `web/lib/forms/generated/<dotted.nsid>.fields.ts`

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde_json::{Map, Value};

const BANNER: &str = "// @generated by layers-codegen — do not edit.\n\
// Regenerate with `cargo run -p layers-codegen -- frontend`.\n\n";

/// Emit Zod + field metadata for every record lexicon under
/// `lexicons/pub/layers/`.
pub fn emit(repo_root: &Path, check_only: bool) -> Result<bool> {
    let lex_root = repo_root.join("lexicons/pub/layers");
    let out_dir = repo_root.join("web/lib/forms/generated");

    let mut emitted: BTreeMap<PathBuf, String> = BTreeMap::new();
    let mut nsids: Vec<String> = Vec::new();

    walk_lexicons(&lex_root, &mut |path| -> Result<()> {
        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("reading {}", path.display()))?;
        let doc: Value = serde_json::from_str(&raw)
            .with_context(|| format!("parsing {}", path.display()))?;
        let Some(nsid) = doc.get("id").and_then(Value::as_str) else {
            return Ok(());
        };
        let Some(main) = doc.get("defs").and_then(|d| d.get("main")) else {
            return Ok(());
        };
        if main.get("type").and_then(Value::as_str) != Some("record") {
            return Ok(());
        }
        let record = match main.get("record") {
            Some(r) => r,
            None => return Ok(()),
        };
        let props = match record.get("properties").and_then(Value::as_object) {
            Some(p) if !p.is_empty() => p,
            _ => return Ok(()),
        };
        let required: Vec<&str> = record
            .get("required")
            .and_then(Value::as_array)
            .map(|arr| arr.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();

        nsids.push(nsid.to_owned());
        emitted.insert(
            out_dir.join(format!("{nsid}.schema.ts")),
            render_zod(nsid, props, &required),
        );
        emitted.insert(
            out_dir.join(format!("{nsid}.fields.ts")),
            render_fields(nsid, props, &required),
        );
        Ok(())
    })?;

    nsids.sort();
    emitted.insert(out_dir.join("index.ts"), render_forms_index(&nsids));

    let mut drift = false;
    if !check_only {
        std::fs::create_dir_all(&out_dir)?;
        for entry in std::fs::read_dir(&out_dir)? {
            let path = entry?.path();
            if path.is_file() && !emitted.contains_key(&path) {
                std::fs::remove_file(&path)?;
            }
        }
    }
    for (path, content) in &emitted {
        let actual = std::fs::read_to_string(path).unwrap_or_default();
        if actual == *content {
            continue;
        }
        if check_only {
            eprintln!("drift in {}", path.display());
            drift = true;
        } else {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, content)?;
        }
    }
    if !check_only {
        println!(
            "wrote forms: {} record lexicons (Zod + field metadata)",
            nsids.len()
        );
    }
    Ok(drift)
}

fn walk_lexicons(root: &Path, visit: &mut impl FnMut(&Path) -> Result<()>) -> Result<()> {
    for entry in std::fs::read_dir(root)
        .with_context(|| format!("reading {}", root.display()))?
    {
        let path = entry?.path();
        if path.is_dir() {
            walk_lexicons(&path, visit)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("json") {
            visit(&path)?;
        }
    }
    Ok(())
}

fn render_forms_index(nsids: &[String]) -> String {
    let mut out = String::from(BANNER);
    out.push_str("/**\n * Barrel of every generated form artefact. Each `<nsid>.schema.ts`\n * exports a Zod schema named `schema`; each `<nsid>.fields.ts` exports a\n * `fields` array of `{ name, kind, label, description, required, ... }`.\n */\n\n");
    out.push_str(&format!(
        "export const FORM_NSIDS: readonly string[] = [\n{}\n];\n\n",
        nsids
            .iter()
            .map(|n| format!("  '{n}',"))
            .collect::<Vec<_>>()
            .join("\n")
    ));
    // Re-export the FormField shape from the first generated fields
    // file so consumers can `import type { FormField } from '@/lib/forms/generated'`.
    if let Some(first) = nsids.first() {
        out.push_str(&format!(
            "export type {{ FormField }} from './{first}.fields.js';\n\n"
        ));
    }
    out.push_str("/**\n * Lazily import the field metadata for an NSID. Used by the\n * generic annotation renderer at runtime.\n */\nexport async function loadFields(nsid: string): Promise<readonly unknown[] | null> {\n  switch (nsid) {\n");
    for n in nsids {
        out.push_str(&format!(
            "    case '{n}':\n      return (await import('./{n}.fields.js')).fields;\n"
        ));
    }
    out.push_str("    default:\n      return null;\n  }\n}\n");
    out
}

fn render_zod(nsid: &str, props: &Map<String, Value>, required: &[&str]) -> String {
    let mut out = String::from(BANNER);
    out.push_str(&format!(
        "// Zod schema mirroring the `{nsid}` record lexicon shape.\n\nimport {{ z }} from 'zod';\n\nexport const schema = z.object({{\n",
    ));
    let mut keys: Vec<&String> = props.keys().collect();
    keys.sort();
    for key in keys {
        let prop = &props[key];
        let inner = zod_for_property(prop);
        let line = if required.contains(&key.as_str()) {
            format!("  {}: {},\n", quote_key(key), inner)
        } else {
            format!("  {}: {}.optional(),\n", quote_key(key), inner)
        };
        out.push_str(&line);
    }
    out.push_str("});\n\nexport type SchemaInput = z.input<typeof schema>;\nexport type SchemaOutput = z.output<typeof schema>;\n");
    out
}

fn zod_for_property(prop: &Value) -> String {
    let ty = prop.get("type").and_then(Value::as_str).unwrap_or("string");
    match ty {
        "string" => {
            let mut z = String::from("z.string()");
            if let Some(min) = prop.get("minLength").and_then(Value::as_u64) {
                z.push_str(&format!(".min({min})"));
            }
            if let Some(max) = prop.get("maxLength").and_then(Value::as_u64) {
                z.push_str(&format!(".max({max})"));
            }
            match prop.get("format").and_then(Value::as_str) {
                Some("uri") => z.push_str(".url()"),
                Some("datetime") => z.push_str(".datetime({ offset: true })"),
                Some("at-uri") => {
                    z.push_str(".regex(/^at:\\/\\//, 'must start with at://')")
                }
                _ => {}
            }
            if let Some(known) = prop.get("knownValues").and_then(Value::as_array) {
                let pretty: Vec<String> = known
                    .iter()
                    .filter_map(Value::as_str)
                    .map(|s| format!("'{}'", escape_single(s)))
                    .collect();
                if !pretty.is_empty() {
                    return format!("z.union([z.enum([{}]), z.string()])", pretty.join(", "));
                }
            }
            z
        }
        "integer" => {
            let mut z = String::from("z.number().int()");
            if let Some(min) = prop.get("minimum").and_then(Value::as_i64) {
                z.push_str(&format!(".min({min})"));
            }
            if let Some(max) = prop.get("maximum").and_then(Value::as_i64) {
                z.push_str(&format!(".max({max})"));
            }
            z
        }
        "number" => "z.number()".into(),
        "boolean" => "z.boolean()".into(),
        "array" => {
            let item = prop
                .get("items")
                .map(zod_for_property)
                .unwrap_or_else(|| "z.unknown()".into());
            let mut z = format!("z.array({item})");
            if let Some(min) = prop.get("minLength").and_then(Value::as_u64) {
                z.push_str(&format!(".min({min})"));
            }
            if let Some(max) = prop.get("maxLength").and_then(Value::as_u64) {
                z.push_str(&format!(".max({max})"));
            }
            z
        }
        "ref" => {
            // Lexicon refs to other defs are opaque at form level —
            // the generated form treats them as arbitrary JSON the
            // user pastes or builds via a sub-form.
            "z.unknown()".into()
        }
        "union" => "z.unknown()".into(),
        "blob" => "z.unknown()".into(),
        "bytes" => "z.unknown()".into(),
        "cid-link" => "z.string()".into(),
        _ => "z.unknown()".into(),
    }
}

fn render_fields(nsid: &str, props: &Map<String, Value>, required: &[&str]) -> String {
    let mut out = String::from(BANNER);
    out.push_str(&format!(
        "// Field metadata for the `{nsid}` record lexicon. The generic\n// annotation renderer + the generated form scaffold both consume this.\n\nexport interface FormField {{\n  readonly name: string;\n  readonly kind:\n    | 'string'\n    | 'enum'\n    | 'integer'\n    | 'number'\n    | 'boolean'\n    | 'datetime'\n    | 'uri'\n    | 'at-uri'\n    | 'array'\n    | 'ref'\n    | 'union'\n    | 'blob'\n    | 'unknown';\n  readonly label: string;\n  readonly description?: string;\n  readonly required: boolean;\n  readonly knownValues?: readonly string[];\n  readonly minLength?: number;\n  readonly maxLength?: number;\n  readonly itemKind?: FormField['kind'];\n  readonly refTarget?: string;\n}}\n\nexport const fields: readonly FormField[] = [\n",
    ));
    let mut keys: Vec<&String> = props.keys().collect();
    keys.sort();
    for key in keys {
        let prop = &props[key];
        let kind = field_kind(prop);
        let label = humanize(key);
        let description = prop
            .get("description")
            .and_then(Value::as_str)
            .map(|s| s.to_owned());
        let item_kind = if kind == "array" {
            prop.get("items").map(field_kind)
        } else {
            None
        };
        let ref_target = prop.get("ref").and_then(Value::as_str).map(str::to_owned);
        let known: Vec<String> = prop
            .get("knownValues")
            .and_then(Value::as_array)
            .map(|arr| {
                arr.iter()
                    .filter_map(Value::as_str)
                    .map(|s| format!("'{}'", escape_single(s)))
                    .collect()
            })
            .unwrap_or_default();

        out.push_str("  {\n");
        out.push_str(&format!("    name: '{key}',\n"));
        out.push_str(&format!("    kind: '{kind}',\n"));
        out.push_str(&format!("    label: {},\n", quote_string(&label)));
        if let Some(d) = description {
            out.push_str(&format!("    description: {},\n", quote_string(&d)));
        }
        out.push_str(&format!(
            "    required: {},\n",
            required.contains(&key.as_str())
        ));
        if !known.is_empty() {
            out.push_str(&format!(
                "    knownValues: [{}],\n",
                known.join(", ")
            ));
        }
        if let Some(min) = prop.get("minLength").and_then(Value::as_u64) {
            out.push_str(&format!("    minLength: {min},\n"));
        }
        if let Some(max) = prop.get("maxLength").and_then(Value::as_u64) {
            out.push_str(&format!("    maxLength: {max},\n"));
        }
        if let Some(ik) = item_kind {
            out.push_str(&format!("    itemKind: '{ik}',\n"));
        }
        if let Some(r) = ref_target {
            out.push_str(&format!("    refTarget: '{r}',\n"));
        }
        out.push_str("  },\n");
    }
    out.push_str("];\n");
    out
}

fn field_kind(prop: &Value) -> String {
    let ty = prop.get("type").and_then(Value::as_str).unwrap_or("string");
    match ty {
        "string" => match prop.get("format").and_then(Value::as_str) {
            Some("uri") => "uri".into(),
            Some("datetime") => "datetime".into(),
            Some("at-uri") => "at-uri".into(),
            _ if prop
                .get("knownValues")
                .and_then(Value::as_array)
                .is_some_and(|a| !a.is_empty()) =>
            {
                "enum".into()
            }
            _ => "string".into(),
        },
        "integer" => "integer".into(),
        "number" => "number".into(),
        "boolean" => "boolean".into(),
        "array" => "array".into(),
        "ref" => "ref".into(),
        "union" => "union".into(),
        "blob" => "blob".into(),
        _ => "unknown".into(),
    }
}

fn humanize(camel: &str) -> String {
    let mut out = String::with_capacity(camel.len() + 4);
    for (i, ch) in camel.chars().enumerate() {
        if i == 0 {
            out.extend(ch.to_uppercase());
        } else if ch.is_uppercase() {
            out.push(' ');
            out.push(ch);
        } else {
            out.push(ch);
        }
    }
    out
}

fn quote_key(k: &str) -> String {
    if k.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && k.chars().next().is_some_and(|c| !c.is_ascii_digit())
    {
        k.to_owned()
    } else {
        format!("'{}'", escape_single(k))
    }
}

fn quote_string(s: &str) -> String {
    format!("'{}'", escape_single(s))
}

fn escape_single(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}
