//! Composable TypeScript IR.
//!
//! Every frontend emitter (`queries`, `mutations`, `forms`, `lenses`)
//! builds a [`TsModule`] out of structured fragments — type
//! references, type aliases, functions, hook definitions — and then
//! lets [`TsModule::emit`] format the whole module deterministically.
//! Avoid concatenating raw TypeScript strings outside this module;
//! when something is genuinely template-shaped, expose a fragment
//! constructor here and call it.
//!
//! The IR is intentionally narrow: it covers the surface the
//! generators need (imports, exported types, const declarations,
//! function declarations) and nothing more. Anything richer should be
//! added here as a typed node before it appears in an emitter.

use std::fmt::Write as _;

const BANNER_LINES: [&str; 2] = [
    "@generated by layers-codegen — do not edit.",
    "Regenerate with `cargo run -p layers-codegen -- frontend`.",
];

/// One TypeScript module file.
pub struct TsModule {
    /// Optional file-level doc comment (single block comment block).
    pub leading_comment: Option<String>,
    pub imports: Vec<TsImport>,
    pub items: Vec<TsItem>,
}

impl TsModule {
    /// Empty module.
    pub fn new() -> Self {
        Self {
            leading_comment: None,
            imports: Vec::new(),
            items: Vec::new(),
        }
    }

    /// Add a single named import or import group.
    pub fn import(&mut self, im: TsImport) -> &mut Self {
        self.imports.push(im);
        self
    }

    /// Add a top-level item.
    pub fn item(&mut self, item: TsItem) -> &mut Self {
        self.items.push(item);
        self
    }

    /// Render the module to a deterministic UTF-8 string.
    pub fn emit(&self) -> String {
        let mut out = String::new();
        // File banner: every generated module starts with the same
        // two `// @generated`-recognisable lines so reviewers and
        // tooling treat them as machine-output.
        for line in BANNER_LINES {
            writeln!(&mut out, "// {line}").unwrap();
        }
        out.push('\n');
        if let Some(c) = &self.leading_comment {
            for line in c.lines() {
                writeln!(&mut out, "// {line}").unwrap();
            }
            out.push('\n');
        }
        // Imports — grouped, deterministic insertion order preserved.
        for im in &self.imports {
            out.push_str(&im.emit());
            out.push('\n');
        }
        if !self.imports.is_empty() {
            out.push('\n');
        }
        for (i, item) in self.items.iter().enumerate() {
            if i > 0 {
                out.push('\n');
            }
            out.push_str(&item.emit());
        }
        out
    }
}

impl Default for TsModule {
    fn default() -> Self {
        Self::new()
    }
}

/// `import { X, Y, type Z } from 'mod'` or `import * as X from 'mod'`.
pub struct TsImport {
    pub from: String,
    pub specifiers: Vec<TsImportSpec>,
}

impl TsImport {
    /// `import { name } from 'mod'`
    pub fn named(from: impl Into<String>, names: impl IntoIterator<Item: Into<String>>) -> Self {
        Self {
            from: from.into(),
            specifiers: names
                .into_iter()
                .map(|n| TsImportSpec::Value(n.into()))
                .collect(),
        }
    }

    /// `import { type T } from 'mod'`
    pub fn types(from: impl Into<String>, names: impl IntoIterator<Item: Into<String>>) -> Self {
        Self {
            from: from.into(),
            specifiers: names
                .into_iter()
                .map(|n| TsImportSpec::Type(n.into()))
                .collect(),
        }
    }

    /// Add a type-only specifier to an existing import.
    pub fn add_type(mut self, name: impl Into<String>) -> Self {
        self.specifiers.push(TsImportSpec::Type(name.into()));
        self
    }

    fn emit(&self) -> String {
        let inside: Vec<String> = self
            .specifiers
            .iter()
            .map(|s| match s {
                TsImportSpec::Value(n) => n.clone(),
                TsImportSpec::Type(n) => format!("type {n}"),
            })
            .collect();
        if inside.iter().any(|s| s.len() > 32) || inside.len() > 3 {
            format!(
                "import {{\n  {},\n}} from '{}';",
                inside.join(",\n  "),
                self.from
            )
        } else {
            format!("import {{ {} }} from '{}';", inside.join(", "), self.from)
        }
    }
}

pub enum TsImportSpec {
    Value(String),
    Type(String),
}

/// Top-level module item.
pub enum TsItem {
    /// `export const NAME = '...' as const;` — the value is emitted verbatim.
    Const {
        doc: Option<String>,
        exported: bool,
        name: String,
        annotation: Option<String>,
        value: String,
    },
    /// `export type Foo = …;`
    TypeAlias {
        doc: Option<String>,
        exported: bool,
        name: String,
        body: String,
    },
    /// `export function foo(p: T): R { … }` (or `async`).
    Function {
        doc: Option<String>,
        exported: bool,
        is_async: bool,
        name: String,
        params: Vec<TsParam>,
        return_type: Option<String>,
        body: String,
    },
    /// Verbatim block (used sparingly for syntactic shapes the IR
    /// does not yet model — keep new emissions out of this variant).
    Raw(String),
    /// Section header comment.
    Section(String),
}

impl TsItem {
    fn emit(&self) -> String {
        match self {
            TsItem::Const {
                doc,
                exported,
                name,
                annotation,
                value,
            } => {
                let mut out = doc_block(doc.as_deref());
                if *exported {
                    out.push_str("export ");
                }
                let annot = annotation
                    .as_deref()
                    .map(|t| format!(": {t}"))
                    .unwrap_or_default();
                writeln!(&mut out, "const {name}{annot} = {value};").unwrap();
                out
            }
            TsItem::TypeAlias {
                doc,
                exported,
                name,
                body,
            } => {
                let mut out = doc_block(doc.as_deref());
                if *exported {
                    out.push_str("export ");
                }
                writeln!(&mut out, "type {name} = {body};").unwrap();
                out
            }
            TsItem::Function {
                doc,
                exported,
                is_async,
                name,
                params,
                return_type,
                body,
            } => {
                let mut out = doc_block(doc.as_deref());
                if *exported {
                    out.push_str("export ");
                }
                if *is_async {
                    out.push_str("async ");
                }
                let plist = if params.is_empty() {
                    String::new()
                } else {
                    let parts: Vec<String> = params.iter().map(TsParam::emit).collect();
                    format!("\n  {},\n", parts.join(",\n  "))
                };
                let ret = return_type
                    .as_deref()
                    .map(|t| format!(": {t}"))
                    .unwrap_or_default();
                writeln!(&mut out, "function {name}({plist}){ret} {{").unwrap();
                for line in body.lines() {
                    if line.is_empty() {
                        out.push('\n');
                    } else {
                        writeln!(&mut out, "  {line}").unwrap();
                    }
                }
                writeln!(&mut out, "}}").unwrap();
                out
            }
            TsItem::Raw(s) => {
                let mut s = s.clone();
                if !s.ends_with('\n') {
                    s.push('\n');
                }
                s
            }
            TsItem::Section(label) => {
                format!("// --- {label} ---\n")
            }
        }
    }
}

/// One function parameter.
pub struct TsParam {
    pub name: String,
    pub ty: String,
    pub default: Option<String>,
    pub optional: bool,
}

impl TsParam {
    pub fn new(name: impl Into<String>, ty: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ty: ty.into(),
            default: None,
            optional: false,
        }
    }

    pub fn optional(mut self) -> Self {
        self.optional = true;
        self
    }

    fn emit(&self) -> String {
        let q = if self.optional { "?" } else { "" };
        match &self.default {
            Some(d) => format!("{name}{q}: {ty} = {d}", name = self.name, ty = self.ty),
            None => format!("{name}{q}: {ty}", name = self.name, ty = self.ty),
        }
    }
}

fn doc_block(doc: Option<&str>) -> String {
    match doc {
        None => String::new(),
        Some(d) if d.contains('\n') => {
            let mut out = String::from("/**\n");
            for line in d.lines() {
                writeln!(&mut out, " * {line}").unwrap();
            }
            out.push_str(" */\n");
            out
        }
        Some(d) => format!("/** {d} */\n"),
    }
}
