//! Emit `web/lib/generated/views.ts`: one TypeScript `interface
//! <Record>View` per `pub.layers.*` record kind, describing the JSON
//! shape the orchestrator returns (the indexed record body plus the
//! `uri/cid/did/rkey/indexedAt` envelope fields).
//!
//! Derived from the lexicons so it cannot drift; covered by the
//! `layers-codegen -- check` drift gate.

use std::fmt::Write as _;
use std::path::Path;

use anyhow::Result;
use serde_json::Value;

use super::registry::collect_records;

/// Map a lexicon property to its TypeScript type for a view interface.
fn ts_type(prop: &Value) -> String {
    let ty = prop.get("type").and_then(Value::as_str).unwrap_or("string");
    // string with knownValues becomes a closed union of literals.
    if ty == "string"
        && let Some(known) = prop.get("knownValues").and_then(Value::as_array)
        && !known.is_empty()
    {
        let variants: Vec<String> = known
            .iter()
            .filter_map(Value::as_str)
            .map(|v| format!("\"{}\"", v.replace('"', "\\\"")))
            .collect();
        return variants.join(" | ");
    }
    match ty {
        "integer" | "number" => "number".to_owned(),
        "boolean" => "boolean".to_owned(),
        "array" => {
            let item = prop
                .get("items")
                .map_or_else(|| "unknown".to_owned(), ts_type);
            format!("Array<{item}>")
        }
        // string / ref / at-uri / datetime / blob all surface as strings;
        // unions and nested objects are opaque to the view layer.
        "union" | "object" => "unknown".to_owned(),
        _ => "string".to_owned(),
    }
}

/// Render `views.ts`.
pub(super) fn render(repo_root: &Path) -> Result<String> {
    let lex_root = repo_root.join("lexicons/pub/layers");
    let records = collect_records(&lex_root)?;

    let mut body = String::from(
        "// @generated by layers-codegen. do not edit.\n\
         // TypeScript view interfaces for every pub.layers.* record kind,\n\
         // derived from the lexicons.\n\n",
    );
    for rec in &records {
        let _ = write!(
            body,
            "/** View type for `{}`. */\nexport interface {} {{\n\
             \x20\x20uri: string;\n\
             \x20\x20cid: string;\n\
             \x20\x20did: string;\n\
             \x20\x20rkey: string;\n\
             \x20\x20indexedAt: string;\n",
            rec.nsid, rec.view_type
        );
        let mut keys: Vec<&String> = rec.props.keys().collect();
        keys.sort();
        for key in keys {
            let prop = &rec.props[key];
            let optional = if rec.required.iter().any(|r| r == key) {
                ""
            } else {
                "?"
            };
            let _ = writeln!(body, "  \"{key}\"{optional}: {};", ts_type(prop));
        }
        body.push_str("}\n\n");
    }
    Ok(body)
}

/// Emit (or check) `web/lib/generated/views.ts`.
///
/// # Errors
/// Propagates lexicon read and write failures.
pub fn emit(repo_root: &Path, check_only: bool) -> Result<bool> {
    let out = repo_root.join("web/lib/generated/views.ts");
    let content = render(repo_root)?;
    super::write_or_check(&out, &content, check_only)
}
