#!/usr/bin/env node
/**
 * Provisions every PDS subaccount the seed catalogue references.
 *
 * @remarks
 * Discovers handles three ways:
 * 1. Hard-coded special-case accounts (`auth.layers.pub`, `foreign.layers.pub`).
 * 2. Every directory under `lexicons/seeds/` (each is a handle).
 *
 * For each handle:
 * - Skip if `notes/pds-secrets/<handle>.env` already exists (idempotent).
 * - Mint a one-shot invite via the admin API.
 * - createAccount under the registry's master e-mail with a freshly
 *   generated password.
 * - Persist the password + DID to `notes/pds-secrets/<handle>.env`.
 *
 * After running, prints the DNS TXT line that should appear at
 * `_lexicon.layers.pub` (pointing at `auth.layers.pub`'s DID) so the
 * OAuth permission-set resolver can find the canonical lexicons.
 *
 * Usage:
 *
 *   PDS=https://pds.layers.pub \
 *   ADMIN_PASSWORD=$LAYERS_PDS_ADMIN_PASSWORD \
 *   EMAIL_DOMAIN=ops.layers.pub \
 *   node layers/scripts/bootstrap-pds.mjs
 */

import { mkdirSync, readdirSync, existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { randomBytes } from 'node:crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, '..');

const PDS = process.env.PDS;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
const EMAIL_DOMAIN = process.env.EMAIL_DOMAIN ?? 'ops.layers.pub';

if (!PDS || !ADMIN_PASSWORD) {
  console.error('Missing required env: PDS, ADMIN_PASSWORD');
  process.exit(1);
}

const SECRETS_DIR = join(REPO_ROOT, 'notes', 'pds-secrets');
mkdirSync(SECRETS_DIR, { recursive: true });

/**
 * Hard-coded special-case handles that don't appear under
 * `lexicons/seeds/<handle>/` because they're derived from existing
 * lexicon JSON files (auth.layers.pub from `lexicons/pub/layers/auth*.json`,
 * foreign.layers.pub from `lexicons/foreign/**`).
 */
const SPECIAL_HANDLES = ['auth.layers.pub', 'foreign.layers.pub'];

function discoverHandles() {
  const handles = new Set(SPECIAL_HANDLES);
  const seedsDir = join(REPO_ROOT, 'lexicons', 'seeds');
  if (existsSync(seedsDir)) {
    for (const entry of readdirSync(seedsDir, { withFileTypes: true })) {
      if (entry.isDirectory()) handles.add(entry.name);
    }
  }
  return [...handles].sort();
}

async function postJson(url, body, headers = {}) {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...headers },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    parsed = text;
  }
  return { ok: res.ok, status: res.status, body: parsed };
}

async function provisionHandle(handle) {
  const credPath = join(SECRETS_DIR, `${handle}.env`);
  if (existsSync(credPath)) {
    console.log(`  ${handle}  (cached)`);
    return;
  }

  const adminAuth = {
    authorization: `Basic ${Buffer.from(`admin:${ADMIN_PASSWORD}`).toString('base64')}`,
  };
  const invite = await postJson(
    `${PDS}/xrpc/com.atproto.server.createInviteCode`,
    { useCount: 1 },
    adminAuth,
  );
  if (!invite.ok) {
    throw new Error(`createInviteCode for ${handle}: ${invite.status} ${JSON.stringify(invite.body)}`);
  }

  const password = randomBytes(24).toString('hex');
  const email = `${handle.replaceAll('.', '-')}@${EMAIL_DOMAIN}`;
  const created = await postJson(`${PDS}/xrpc/com.atproto.server.createAccount`, {
    email,
    handle,
    password,
    inviteCode: invite.body.code,
  });
  if (!created.ok) {
    throw new Error(`createAccount for ${handle}: ${created.status} ${JSON.stringify(created.body)}`);
  }

  const did = created.body.did;
  const env = [
    `# auto-generated by bootstrap-pds.mjs; do not commit`,
    `handle=${handle}`,
    `did=${did}`,
    `email=${email}`,
    `password=${password}`,
    '',
  ].join('\n');
  writeFileSync(credPath, env, { mode: 0o600 });
  console.log(`  ${handle}  →  ${did}`);
  return did;
}

async function main() {
  const handles = discoverHandles();
  console.log(`provisioning ${handles.length} subaccounts on ${PDS}`);
  let authDid;
  for (const handle of handles) {
    const did = await provisionHandle(handle);
    if (handle === 'auth.layers.pub') authDid = did;
  }

  // Re-read auth.layers.pub's env to print the DNS TXT pointer
  // even if the bootstrap was a no-op for that handle.
  const authEnv = join(SECRETS_DIR, 'auth.layers.pub.env');
  if (!authDid && existsSync(authEnv)) {
    const text = require('node:fs').readFileSync(authEnv, 'utf8');
    const match = text.match(/^did=(\S+)$/m);
    if (match) authDid = match[1];
  }

  console.log('\nDone.');
  if (authDid) {
    console.log(`\nAdd this DNS TXT record at  _lexicon.layers.pub:`);
    console.log(`  did=${authDid}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
