/**
 * Unit tests for the layers/codegen pipeline.
 *
 * The codegen script is the single source of truth for src/types/ modules,
 * the web view registry, and lens scaffolds. Regressions here break every
 * downstream consumer, so we exercise the full emit cycle against the real
 * lexicons and assert shape of the output.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = join(__dirname, '..', '..', '..');
const SCRIPT = join(ROOT, 'codegen', 'generate.mjs');

describe('codegen: generate.mjs', () => {
  it('runs end-to-end on the real lexicons and exits 0', () => {
    const out = execFileSync('node', [SCRIPT], { cwd: ROOT, encoding: 'utf8' });
    expect(out).toMatch(/wrote src\/types\/ \(26 records\)/);
    expect(out).toMatch(/wrote lenses\/ \(26 protolens specs\)/);
    expect(out).toMatch(/wrote 26 record kinds/);
  });

  it('emits a src/types file per mapped record with stable exports', () => {
    const expected = [
      'persona',
      'corpus',
      'expression',
      'annotation-layer',
      'cluster-set',
      'alignment',
      'segmentation',
      'ontology',
      'type-def',
      'graph-node',
      'graph-edge',
      'graph-edge-set',
      'eprint',
      'data-link',
      'media',
      'changelog-entry',
      'corpus-membership',
      'experiment-def',
      'judgment-set',
      'agreement-report',
      'resource-entry',
      'resource-collection',
      'collection-membership',
      'template',
      'template-composition',
      'filling',
    ];
    for (const slug of expected) {
      const path = join(ROOT, 'src', 'types', `${slug}.ts`);
      expect(existsSync(path), `missing ${slug}.ts`).toBe(true);
      const src = readFileSync(path, 'utf8');
      expect(src, `${slug}`).toMatch(/Generated by layers\/codegen\/generate\.mjs/);
      expect(src, `${slug}`).toMatch(/import { z } from 'zod';/);
      expect(src, `${slug}`).toMatch(/RecordSchema = z\.object/);
      expect(src, `${slug}`).toMatch(/toRecordView|toPersonaView|to.+View/);
    }
  });
});

describe('codegen: record-registry output', () => {
  const registryPath = join(ROOT, 'web', 'lib', 'generated', 'record-registry.ts');

  it('registers exactly 26 record kinds', () => {
    const src = readFileSync(registryPath, 'utf8');
    const matches = src.match(/"nsid": "pub\.layers\./g) ?? [];
    expect(matches.length).toBe(26);
  });

  it('discovers canonical list/get endpoints even for irregular plurals', () => {
    const src = readFileSync(registryPath, 'utf8');
    expect(src).toContain('"listEndpoint": "pub.layers.corpus.listCorpora"');
    expect(src).toContain('"listEndpoint": "pub.layers.changelog.listEntries"');
    expect(src).toContain('"listEndpoint": "pub.layers.media.listMedia"');
    expect(src).toContain('"getEndpoint": "pub.layers.changelog.getEntry"');
    expect(src).toContain('"getEndpoint": "pub.layers.corpus.getMembership"');
  });

  it('exposes listParams with required + optional flags from each query lexicon', () => {
    const src = readFileSync(registryPath, 'utf8');
    // listCorpora requires `repo`
    const corpusMatch = src.match(/"listEndpoint": "pub\.layers\.corpus\.listCorpora",[\s\S]*?"listParams": \[[\s\S]*?\]/);
    expect(corpusMatch).not.toBeNull();
    expect(corpusMatch![0]).toContain('"name": "repo"');
    expect(corpusMatch![0]).toContain('"required": true');
    // listCorpora accepts optional `language` and `domain`
    expect(corpusMatch![0]).toContain('"name": "language"');
    expect(corpusMatch![0]).toContain('"name": "domain"');
  });

  it('exports resolveKindFromUri that handles at-uri shape', () => {
    const src = readFileSync(registryPath, 'utf8');
    expect(src).toMatch(/function resolveKindFromUri\(uri: string\)/);
    expect(src).toMatch(/\/\^at:\\\/\\\/\[\^\/]\+\\\/\(\[\^\/]\+\)\\\//);
  });
});

describe('codegen: generated views.ts', () => {
  const viewsPath = join(ROOT, 'web', 'lib', 'generated', 'views.ts');

  it('exports one view interface per record kind', () => {
    const src = readFileSync(viewsPath, 'utf8');
    const exports = src.match(/^export interface \w+View \{/gm) ?? [];
    expect(exports.length).toBe(26);
  });

  it('emits enum unions for fields with knownValues', () => {
    const src = readFileSync(viewsPath, 'utf8');
    // annotationLayer.kind has knownValues including "token-tag"
    expect(src).toMatch(/"token-tag" \| "span" \| "relation"/);
  });
});

describe('codegen: lens scaffolds', () => {
  it('emits a lens.json per record with table extension metadata', () => {
    const samples = [
      'pub.layers.persona.persona.lens.json',
      'pub.layers.corpus.corpus.lens.json',
      'pub.layers.resource.collectionMembership.lens.json',
    ];
    for (const name of samples) {
      const p = join(ROOT, 'lenses', name);
      expect(existsSync(p), name).toBe(true);
      expect(statSync(p).size).toBeGreaterThan(0);
      const parsed = JSON.parse(readFileSync(p, 'utf8'));
      expect(parsed.$type).toBe('panproto.protolens');
      expect(parsed.extensions.table).toMatchObject({ row_struct: expect.any(String) });
      expect(parsed.extensions.table.columns).toEqual(
        expect.arrayContaining([expect.objectContaining({ name: 'uri' })]),
      );
    }
  });
});
