apiVersion: v1
kind: Service
metadata:
  name: layers-api
  namespace: layers
  labels:
    app: layers-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: layers-api
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
